- 김동하/2주차/[백준 1309] 동물원.java
- 김동하/2주차/[백준 1629] 곱셈.java
- 김동하/2주차/[백준 17845] 수강 과목.java
- 김동하/2주차/[백준 18352] 특정 거리의 도시 찾기.java
- 김동하/2주차/[백준 21608] 상어 초등학교.java
---
---
**문제 난이도**
골드 5
**문제 유형**
구현
**접근 방식 및 풀이**
- ### 문제를 풀 때 든 생각
인풋의 사이즈를 확인해 보니 매우 작은걸 확인할 수 있다.
그러므로 이는 단순히 문제의 조건에 맞게 구현만 하면 되는 문제이다.
- ### 구상
1. 각 관심사 별로 메서드를 추출하여 편하게 완전 탐색을 돌린다.
2. 관심사는 다음과 같다
1. 가장 많은 친구가 인접해 있는 곳을 탐색하는 관심사
2. 빈칸이 가장 많은 곳을 탐색하는 관심사
3. 행 과 열이 작은순으로 차례로 정렬하는 관심사
3. 관심사가 다 정해졌다면 순차적으로 메서드를 구현하면 된다. 
파라미터로 각 단계별로 선정된 자리들을 list형태로 넘겨받고, 그 list내에서 다음 관심사에 대해 행동을 취하면 쉽게 구현할 수 있는 문제였다.
다만 자바로 구현이 처음이라 어려운 부분이 있었다면, list를 정렬할 때 기준에 맞춰서 정렬하기 위한 comparator 클래스를 작성하는데 어려움을 겪었다. 코드는 다음과 같다.
``` java
static class NodeComparator implements Comparator<Node> {
@Override
public int compare(Node o1, Node o2) {
if (o1.x != o2.x) {
return Integer.compare(o1.x, o2.x); // x값 기준으로 비교
}
return Integer.compare(o1.y, o2.y); …
```
> [김동하-2주차 알고리즘 스터디]

- 김민진/1주차/[Baekjoon-10844] 쉬운 계단 수.java
- 김민진/1주차/[Baekjoon-17070] 파이프 옮기기 1.java
- 김민진/1주차/[Baekjoon-17471] 게리맨더링.java
- 김민진/1주차/[Baekjoon-17472] 다리 만들기 2.java
- 김민진/1주차/[Baekjoon-2578] 빙고.java
- 김민진/1주차/inital.txt
---
---
**문제 난이도**
골드 1
**문제 유형**
`구현`  `그래프`  `BFS`  `MST`
**접근 방식 및 풀이**
1. BFS를 활용해 섬을 그래프 노드화
- 너비우선탐색을 활용하여 섬을 1부터 라벨링
- 부모 노드는 자기자신으로 설정(추후 섬들이 연결되었는지 확인할 때 활용)
2. 섬의 상하좌우를 탐색
- `MSTNode`:
- `from`: 댜리의 시작점
- `to`: 다리의 도착지점
- `len`: 다리 길이
- `compareTo`: 다리 길이를 기준으로 정렬하기 위해 오버라이드
- 섬의 가장자리인 경우 바다쪽을 향해 탐색 시작
- 다리를 건설할 수 있는 경우 우선순위 큐에 저장
3. `Kruskal` 알고리즘을 사용하여 총 다리 길이의 최소값을 찾음
- `Union-Find`를 활용해 다리가 연결되었는지 확인
- 부모가 같은 경우 연결된 것
- 연결되지 않았다면 연결
- 현재 노드의 다리 길이를 `sum`에 저장
- 부모 일치시킴
4. 다리의 수가 `섬의 수 - 1`인 경우 답이 있는 것이므로 `sum` 출력
- 아닌 경우 -1 출력
---
**문제 난이도**
골드 3
**문제 유형**
`DFS`  `BFS`
**접근 방식 및 풀이**
- `DFS`를 활용하여 구역을 나눔
- 먼저 1로 라벨링한 후 재귀가 종료되면 2로 라벨링
- 모든 노드를 방문했다면, 각 구역의 인구 수를 구함
- 구역이 알맞게 나누어졌는지 확인
- `BFS`를 활용, 탐색이 끝나는 경우 구역 수 + …
>  [김민진-1주차 알고리즘 스터디]

- 문한결/1주차/문제1-다리 만들기2.java
- 문한결/1주차/문제2-게리맨더링.java
- 문한결/1주차/문제3-파이프 옮기기.java
- 문한결/1주차/문제4-빙고.java
- 문한결/1주차/문제5-쉬운 계단수.java
---
---
**문제 난이도**
골드1
**문제 유형**
```구현``` , ```MST``` , ```BFS```
**접근 방식 및 풀이**
이 문제는 크게 아래의 풀이로 진행됩니다.
- 각 섬을 숫자로 구분합니다
- 각 섬을 구분 할때는 bfs를 통해서 2,3,4...로 구분
- 모든 곳을 탐색하며 **두 섬과 거리**를 저장합니다.
- ```Bridge```라는 두 섬을 저장하는 클래스를 만들고, ```Bridge```를 키로, 하고 Integer(섬사이의 거리)를 value로 하는 ```HashMap```을 만들고 이 곳에 값을 저장합니다.
- 가로로 놓인 다리의 거리는 ```insertRightBridge```메서드를,
- 세로로 놓인 다리의 거리는  ```insertDownBridge```메서드를 이용해서 저장합니다.
-  ```insertRightBridge```,  ```insertDownBridge```내에서는 각 섬사이의 거리의 최솟값을 구해서 저장하기 위한 과정을 거칩니다.
- 위에서 구한 ```Hashmap```의 값을 거리 순으로 정렬하고 ```MST```인 **Krusukal** 알고리즘을 사용해서 현재 섬이 다 연결되어 있을 때의 최소의 거리를 찾습니다.
---
**문제 난이도**
골드3
**문제 유형**
```DFS``` , ```BFS```
**접근 방식 및 풀이**
이 문제에서 가장 중요한 부분은```dfs```로 모든 구역을 돌면서 선거구를 두개로 나누는 …
> [문한결-1주차 알고리즘 스터디]

- 김동하/3주차/[백준 13305] 주유소.java
- 김동하/3주차/[백준 16236] 아기 상어.java
- 김동하/3주차/[백준 1931] 회의실 배정.java
- 김동하/3주차/[백준 2981] 검문.java
- 김동하/3주차/[백준 9020] 골드바흐의 추측.java
---
---
**문제 난이도**
골드 3
**문제 유형**
구현
**접근 방식 및 풀이**
상어시리즈는 나름 편하게 생각할 수 있는게 문제에서 시키는것을 따라가며 그대로 구현하기만 하면 된다고 생각해서 문제를 쭉 읽고 하나씩 구현해 나갔다.
1. 먹을 수 있는 물고기를 다 찾음
2. 우선순위에 따라서 물고기를 먹음
3. 먹기에 성공했으면 다시 시작하고, 실패했다면 종료 후 현재까지 먹은 물고기 수를 출력함.
---
**문제 난이도**
실버 2
**문제 유형**
수학
**접근 방식 및 풀이**
결국 두개의 소수로 나누어야 하나의 수가 정해지면, 나머지 하나의 수는 `N - 정해진수` 이므로 처음 시작을 n/2에서부터 시작해서 하나씩 줄여가며 탐색을 했다.
1. n / 2에서부터 반복문을 실행하면서 0이상일 때 까지 실행.
2. 현재 탐색중인 수가 소수인지를 확인
1. 만약 소수가 아니라면 다시 탐색 시작
2. 소수라면 해당 두 수를 출력하고 종료
---
**문제 난이도**
골드 4
**문제 유형**
수학
**접근 방식 및 풀이**
처음 봤을땐 결국 최대공약수를 구하는 문제일거 같다고 생각을 했는데 확신은 없었음.
그래서 어차피 구현에 오래 걸리지도 않는데 그냥 구현해보자 하고 생각하여 구현 시작
1. 모든 수들의 최대공약수를 구하기 위해 초기값 세팅 후 반복문 시작
1. 초기값은 0번인덱스와 1번인덱스 값의 GCD
2. 초기값과 그 다음 인덱스의 GCD를 구해나감
2. 이렇게 모든 수의 GCD가 …
> [김동하-3주차 알고리즘 스터디]

- 김민진/1주차/inital.txt
- 김민진/2주차/[Baekjoon-1309] 동물원.java
- 김민진/2주차/[Baekjoon-1629] 곱셈.java
- 김민진/2주차/[Baekjoon-17845] 수강 과목.java
- 김민진/2주차/[Baekjoon-18352] 특정 거리의 도시찾기.java
- 김민진/2주차/[Baekjoon-21608] 상어 초등학교.java
---
---
**문제 난이도**
골드 5
**문제 유형**
`구현`
**접근 방식 및 풀이**
1. 좌석을 탐색하며 가장 최선의 좌표를 찾는다
- 우선순위: 친구 수 > 빈 자리 > 행 > 열
- `compareTo()` 메소드로 우선순위 적용
```java
// 우선순위 큐에 넣을 노드
static class	Student implements Comparable<Student> {
int	id;
int	x;
int	y;
int	friendsNearby;
int	emptySeatsNearby;
Student(int id, int x, int y, int friendsNearby, int emptySeatsNearby) {
this.id = id;
this.x = x;
this.y = y;
this.friendsNearby = friendsNearby;
this.emptySeatsNearby = emptySeatsNearby;
}
}
```
- 모든 좌석 확인 후 `poll()` 한 노드의 좌표가 최적의 좌석
2. 만족도 계산
- 좌석도를 확인하며 친구 수에 따른 만족도 합산
- `SATISFACTION` 배열을 선언하여 친구 수에 대응하는 만족도를 바로 구할 수 있도록 함
```java
private static final int[]	SATISFACTION = { 0, 1, 10, 100, 1000 };
```
---
**문제 난이도**
골드 5
**문제 유형**
`DP` `배낭 문제`
**접근 …
> [김민진-2주차 알고리즘 스터디]

- 문한결/2주차/곱셈.java
- 문한결/2주차/동물원.java
- 문한결/2주차/상어초등학교.java
- 문한결/2주차/수강 과목.java
- 문한결/2주차/특정 거리의 도시찾기.java
---
---
**문제 난이도**
골드5
**문제 유형**
```구현```
**접근 방식 및 풀이**
해당 문제는 읽으면서, 상어의 자리를 배정해주는 구현 문제의 느낌을 받았습니다.
상어의 자리는 다음과 같은 프로세스로 정해줍니다.
- 비어 있는 칸 중 좋아하는 학생이 인접한 칸에 가장 많은 칸으로 자리를 이동->```assignP1()```
- 비어있는 칸을 순회하면서 인접한 칸을 본다.     ->```searchAdj()```
- 인접한 칸이 가장 많은 칸들의 좌표를 저장해서 이를 반환
- 1의 결과가 많다면,현재의 칸에서 인접한 칸을 구하고, 칸의 갯수가 큰 것으로 배정->``` assignP2()```
- 위의 결과도 많다면, 행이 가장 작은 순으로, 행이 같다면 열이 같은 곳으로 자리를 배정한다. 
단계를 정하고 문제풀이를 들어가니 수월하게 풀 수 있었습니다.
또한 여기서 학생이 선호하는 학생의 번호를 ```students``` 라는 ```Map```을 이용하였는데, 
```Map```의 구현체로 ```LinkedHashMap```을 사용하였습니다. 일반적인 ```HashMap```은 순서를 보장하지 못하지만, ```LinkedHashMap```에서는 순서를 보장할 수 있기 때문입니다.
---
**문제 난이도**
골드5
**문제 유형**
```배낭 문제```
**접근 방식 및 풀이**
공부시간을 넘지 않으면서 만들 수 있는 과목의 중요도의 합을 구하는 문제입니다.
문제의 포맷이 딱 …
> [문한결-2주차 알고리즘 스터디]

- 김민진/1주차/inital.txt
- 김민진/3주차/[Baekjoon-13305] 주유소.java
- 김민진/3주차/[Baekjoon-16236] 아기상어.java
- 김민진/3주차/[Baekjoon-1931] 회의실 배정.java
- 김민진/3주차/[Baekjoon-2981] 검문.java
- 김민진/3주차/[Baekjoon-9020] 골드 바흐의 추측.java
---
---
**문제 난이도**
골드 3
**문제 유형**
`구현` `그래프` `BFS`
**접근 방식 및 풀이**
처음에는 우선순위 큐를 사용하여 풀이하였으나 코드를 완성하고 보니 필요가 없어 수정함
🦈 `Shark` 클래스
```java
static class Shark {
int x;
int y;
int size;
int eatenFish;
Shark(int x, int y, int size, int eatenFish) {
this.x = x;
this.y = y;
this.size = size;
this.eatenFish = eatenFish;
}
public void updateInfo(int x, int y) {
this.x = x;
this.y = y;
eatenFish++;
if (eatenFish == size) {
size++;
eatenFish = 0;
}
}
}
```
→ 좌표, 크기, 먹은 물고기 수를 저장
: 만약 크기만큼의 물고기를 먹은 경우 크기를 키워주는 `updateInfo()` 메서드 정의
📦 `Block` 클래스
```java
static class Block {
int x;
int y;
int time;
Block(int x, int y, int time) {
this.x = x;
this.y = y;
this.time = time;
}
}
```
→ 각 칸의 좌표와 상어가 도달하는 데 걸리는 시간을 저장하는 클래스
: 너비 우선 탐색에 사용
- 물고기를 더 …
> [김민진-3주차 알고리즘 스터디]

- 문한결/3주차/검문.java
- 문한결/3주차/골드 바흐의 추측.java
- 문한결/3주차/아기상어.java
- 문한결/3주차/주유소.java
- 문한결/3주차/회의실 배정.java
---
---
**문제 유형**
```구현```,```bfs```
**문제 난이도**
골드3
**접근 방식 및 풀이**
처음에 문제를 풀기전에 각 메서드별로 아래와 같이 설계를 한 후에 들어갔습니다.
```
* 아기 상어 초기 크기는 2 상하좌우로 인접한 한칸을 이동할 수 있음.
* 자기보다 작은 놈만 먹을 수 있음. 
* 자신의 크기와 같은 수의  물고기를 먹으면 크기가 커짐 
* 메서드 1-> 더이상 먹을 물고기가 공간에 없다면 끝.
* 메서드 2-> 먹을 수 있는 물고기가 1마리라면, 이걸 먹으러감
* 메서드 3-> 1마리 보다 많다면 거리가 가장 가까운 물고기를 먹으러감-> 거리는 최소 거리기준임.
* 메서드 4-> 거리가 가까운 물고기가 많다면 가장 위에 있는 물고기 이것도 같다면 가장 왼쪽.
* 메서드 5-> 물고기를 먹을 때마다 경험지가 오른다.경험치가 크기와 같다면 레벨업.
```
메서드 1은 ```returnEnabledFish()```
메서드 2는 ```eatFishInOne()```
메서드 3은 ```eatFishInMany()```
메서드 4는  ```eatFishInMany()```에 구현,
메서드 5는``` Shark```클래스를 만들어서 이 내부에서, 상어 위치가 바뀔 때마다 체크했습니다.
상어가 크기가 같은 물고기를 지나갈 수 있다는 조건을 못 봐서 생각보다 시간이 걸렸기에
조건을 좀 더 꼼꼼히 보고, 관찰해야겠다는 생각했습니다.
뭔가 각 메서드들 사이에 있는 …
> [문한결-3주차 알고리즘 스터디] 

- 박준서/2주차/[Baekjun-1309]동물원.java
- 박준서/2주차/[Baekjun-1629]곱셈.java
- 박준서/2주차/[Baekjun-17845]수강과목.java
- 박준서/2주차/[Baekjun-18352]특정거리의도시찾기.java
- 박준서/2주차/[Baekjun-21608]상어초등학교.java
---
---
**문제 난이도**\
Gold 5
**문제 유형**\
구현
처음에 너무 어렵게 생각해서 많은 결과 행렬이 나오는줄 알았는데 조건에 행번호, 열번호 정렬 조건도 있는걸 늦게 찾았다
1. 학생 한명 정보를 받을 때마다 조건에 부합하는 좌표를 찾는다\
1-1. 모든 점을 검사해서 arraylist에 저장한 후 정렬해서 찾음
2. 계산할 때 cnt==0 때문에 Math.pow() 깔끔하게 못한거 아쉽다
---
**문제 난이도**\
Gold 5
**문제 유형**\
DP
배낭문제가 정확히 어떤 유형인지 잘 모르기도 해서 그냥 DP로 풂
순서대로 값을 받아서 DP 배열에 1행에 첫번째 과목, 2행에 두번째 과목 순서로 쌓아 올리듯이 비교해서 구했다
---
**문제 난이도**\
Silver 1
**문제 유형**\
DP
n타일 문제보다 이 문제가 DP 익히기 좋은거 같음
1. 전 단계에 비어있을 때 -> 오른쪽 + 왼쪽 + 비우기
2. 전 단계에 오른쪽 -> 왼쪽 + 비우기
3. 전 단계에 왼쪽 -> 오른쪽 + 비우기
---
**문제 난이도**\
Silver 1
**문제 유형**\
분할정복
빠른 피보나치 계산인가 그 문제 풀었던 기억이 있어서 빠르게 풀었다.
1. 지수가 짝수면 f(B/2) \* f(B/2)
2. 지수가 홀수면 f(B/2) \* f(B/2) \* A
3. f(1) 일때 A return
---
**문제 난이도**\
Silver 2
**문제 유형**\
BFS
MST인거 같았는데 어짜피 …
> [박준서-2주차 알고리즘 스터디]

- 박준서/3주차/[Baekjun-13305]주유소.java
- 박준서/3주차/[Baekjun-16236]아기상어.java
- 박준서/3주차/[Baekjun-1931]회의실배정.java
- 박준서/3주차/[Baekjun-2981]검문.java
- 박준서/3주차/[Baekjun-9020]골드바흐의추측.java
---
---
**문제 난이도**\
Gold 3
**문제 유형**\
구현
시뮬레이션 문제중에 그나마 재미있는 문제인것 같다.
1. BFS of DFS로 상어가 먹을 수 있는 물고기를 찾음
2. 거리가 가까운 순, 위쪽, 왼쪽 순으로 정렬
3. 선택한 물고기를 먹으며 1,2 반복
---
**문제 난이도**\
Silver 2
**문제 유형**\
수학
골드바흐 추측으로 먼저 소수 배열을 찾아놓고 진행해야 됨\
매번 찾는 방식 isPrime 방식으로는 시간초과
1. 소수 배열 구현
2. 차이가 적은 수가 답이므로 num/2부터 시작
---
**문제 난이도**\
Gold 4
**문제 유형**\
수학
사실 이문제는 도저히 답이 안나와서 블로그를 보고 풂\
나머지가 같다는 것을 가정하고 풀어야 함\
ex) 14 = 6 \* 2 + 2, 26 = 6 \* 4 + 2
1. 위 예시에서 나머지를 제거하기 위해서 두 수를 빼줌
2. nums[i]-nums[i+1]을 순차적으로 구해 최대공약수를 찾음
3. 찾은 최대공약수의 약수들이 답
---
**문제 난이도**\
Gold 5
**문제 유형**\
그리디
그리디에서 가장 유명한 문제인 것 같다
1. 시작시간 오름차순, 끝나는시간 오름차순으로 정렬
2. 순서대로 배정을 할 수 있으면 추가
---
**문제 난이도**\
Silver 3
**문제 유형**\
그리디
처음에는 O(N^2)로 모든 케이스를 커버하려 했는데 시간초과가 남 -> O(N)으로 바꿔야 함
1. 예를 들어 5 …
> [박준서-3주차 알고리즘 스터디]

- 박예진/1주차/[백준 10844] 쉬운 계단 수.java
- 박예진/1주차/[백준 17070] 파이프 옮기기 1.java
- 박예진/1주차/[백준 17471] 게리맨더링.java
- 박예진/1주차/[백준 17472] 다리 만들기 2.java
- 박예진/1주차/[백준 2578] 빙고.java
- 박예진/2주차/[백준 1629] 곱셈.java
- 박예진/2주차/[백준 17845] 수강과목.java
- 박예진/2주차/[백준 18352] 특정 거리의 도시 찾기.java
- 박예진/2주차/[백준 21608] 상어 초등학교.java
---
---
**문제 난이도**
골드1
**문제 유형**
유니온 파인드, MST 크루스칼, BFS, 우선순위큐
**접근 방식 및 풀이** 
1. 각 군집들 index 표시하기 (BFS)
2. 0 아닌 것들 탐색해 간선 우선순위큐에 넣기 (구현)
2-1. idx -> idx 같은 군집일 땐 무시
2-2. 0이면 같은 방향으로 직진해 다른 군집이며, 2칸 이상일 경우에만 우선순위 큐에 넣음
3. 유니온 파인드 하면서 모든 정점 부모 같아질 때까지 부모 노드가 다를 때만 (사이클x)
---
**문제 난이도**
골드3
**문제 유형**
유니온 파인드, 조합 DFS
**접근 방식 및 풀이**
먼저 문제에 대해서 간단히 설명해보자면 다음과 같이 그래프가 주어졌을 때
2가지 구역으로 나눠서, 두 구역의 인구수 차이의 최솟값을 구하는 문제이다.
여기서 유니온 파인드 알고리즘을 생각할 수 있었다.
문제의 조건으로는 각 구역은 1개 이상의 지역으로 이루어져야된다고 한다.
(1) (2, 3, 4, 5, 6)
(2) (1, 3, 4, 5, 6)
...
(1, 2) (3, 4, 5, 6)
(1, 3) (2, 4, 5, 6)
(1, 4) (2, 3, 5, 6)
...
(1, 2, 3) (4, 5, 6)
(1, 2, 4) (3, 5, 6)
이런 식으로 2가지 구역이 나눠질 수 있어서
지역의 개수 N개에서
최소 지역의 개수인 1부터 최대 N / 2개까지 뽑는 조합을 생각할 수 있었다.
각 조합일 경우
방문한 것과 방문하지 …
> [박예진-1주차 알고리즘 스터디]

- 박예진/3주차/[백준 13305] 주유소.java
- 박예진/3주차/[백준 16236] 아기 상어.java
- 박예진/3주차/[백준 1931] 회의실 배정.java
- 박예진/3주차/[백준 2981] 검문.java
- 박예진/3주차/[백준 9020] 골드바흐의 추측.java
---
---
**문제 난이도**
골드3
**문제 유형**
시뮬레이션, BFS
**접근 방식 및 풀이**
java로 알고리즘을 풀기 시작한 이후로부터 어떤 것을 class로 만들 것인지 생각한다.
이 문제에서 class는 Fish, Shark, 좌표를 나타내는 Node로 구성했다.
다음으로 물고기가 없을 때까지 반복을 돌렸다.
모든 좌표를 반복문으로 돌리고, 물고기일때 현재 상어위치와 물고기를 bfs 돌려 dist를 구한다.
그리고 dist가 -1 (아기 상어가 물고기에게 접근할 수 없는 경우) 만 제외하고 우선순위 큐에 넣어 준다.
(처음엔 넣자마자 틀렸었는데, 이 예외를 생각하지 못했었다)
다음과 같은 조건이 있기 때문에 Fish class를 만들 때 `Comparable` interface를 상속받고
`compareTo`를 오버라이딩 해서 자동 정렬되게 구현했다.
``` java 
/*
* 거리가 가장 가까운 물고기
* 가장 위에 있는 물고기
* 가장 왼쪽에 있는 물고기
* */
@Override
public int compareTo(Fish fish) {
if (this.dist != fish.dist) return this.dist - fish.dist; // 거리 오름차순
else if (this.x != fish.x) return this.x - fish.x; // 위쪽
else return this.y - fish.y; // 왼쪽
}
```
그러면 이제, 우선순위 큐의 가장 peek는 …
> [박예진-3주차 알고리즘 스터디]

- 박준서/4주차/[Baekjun-11478]서로다른부분문자열의개수.java
- 박준서/4주차/[Baekjun-1254]팰린드롬만들기.java
- 박준서/4주차/[Baekjun-1865]웜홀.java
- 박준서/4주차/[Baekjun-19236]청소년상어.java
- 박준서/4주차/[Baekjun-5972]택배배송.java
---
---
**문제 난이도**\
Gold 2
**문제 유형**\
구현
포인터가 아닌 자바의 Call By Reference를 사용해서 복잡했다
1. 처음 입력을 받을 때 ArrayList에 Fish 객체로 저장했다\
1-1. Fish는 x,y,direction, alive를 멤버로 갖는다\
Fish의 번호는 ArrayList의 인덱스로 대체
2. 현재 물고기 위치 정보 행렬의 0,0 정보를 상어로 바꾼다\
(항상 0,0부터 먹기 때문에)
3. Fish의 순차적인 움직임 move()와 Fish 위치정보 행렬 갱신 setMatrix()
4. dfs를 통한 백트래킹으로 상어의 움직임에 대한 분기점을 처리해줬다
!! 주의사항 !!\
메소드에 ArratList<Fish>를 매개변수로 널어줬을 때 Call By Reference로 넘어가기 때문에\
객체 하나씩 깊은 복사를 해줘야 한다
---
**문제 난이도**\
Gold 5
**문제 유형**\
다익스트라
시작 정점이 정해져 있고 최단거리를 구하는 문제여서 다익스트라 알고리즘을 사용했다
1. 시작 정점 1을 우선순위 큐에 넣는다
2. 우선순위 큐의 top()값을 현재 정점으로 지정하고 이동할 수 있고,\
거리가 짧은 이동방법을 찾는다
3. 이동 가능한 모든 정점에 도착할 때 까지 2번 반복
---
**문제 난이도**\
Gold 3
**문제 유형**\
벨만-포드
벨만포드 알고리즘이 생각나지 않아서 알고리즘은 검색해 풀었다
정점이 4개일 때 1에서 모든 정점에 …
> [박준서-4주차 알고리즘 스터디]

- 김동하/3주차/[백준 13305] 주유소.java
- 김동하/3주차/[백준 16236] 아기 상어.java
- 김동하/3주차/[백준 1931] 회의실 배정.java
- 김동하/3주차/[백준 2981] 검문.java
- 김동하/3주차/[백준 9020] 골드바흐의 추측.java
- 김동하/4주차/[백준 11478] 서로 다른 부분 문자열의 개수.java
- 김동하/4주차/[백준 1254] 팰린드롬 만들기.java
- 김동하/4주차/[백준 1865] 웜홀.java
- 김동하/4주차/[백준 19236] 청소년 상어.java
- 김동하/4주차/[백준 5972] 택배 배송.java
---
---
**문제 난이도**
골드 2
**문제 유형**
구현
**접근 방식 및 풀이**
- ### 문제를 풀 때 든 생각
역시나 그냥 따라가면서 풀면 되는문제. 하지만 이번엔 배열이 항상 달라지므로 배열을 파라미터로 넘겨 줄 필요성을 느꼈다.
이때, 자바로 알고리즘을 푼 지 얼마 안됐어서 배열 복사에서 난항을 많이 겪었다.
자바는 모든 값이 callByValue!! 배열을 넘길 때 callByReference처럼 느껴진 것은 value로서 배열의 주소값을 넘겨주기 때문에 그렇게 느껴졌던 것이다.
- ### 구상
1. 맵 arr에는 해당 칸의 물고기의 번호와 방향에 대한 정보를 가진다.
2. findIdx 메서드는 완전탐색을 하며 해당 번호의 물고기가 있는 노드를 반환해준다.
이때, 물고기를 찾지 못하면(잡아 먹혔으면) -1,-1을 반환해준다.
3. 완전탐색을 하며 각각의 물고기를 findIdx로 물고기를 찾아온 후 -1이 아니라면(아직 잡아먹히지 않았다면)  이동을 이동 가능한 칸을 찾아본 후 가능한 칸이 있다면 그 칸과 스왑해준다.
4. 모든 물고기의 이동이 끝났다면, 상어가 잡아먹기 시작한다. 
물고기의 이동 실행, 상어가 잡아먹는 것은 배열을 덮어씌우기에 재귀적으로 구성햇다.
상어가 잡아먹기에 성공했다면 다시 물고기의 이동부터 반복하고, 실패했다면 ans값을 최대값으로 업데이트 한 후 재귀를 빠져나간다.
---
**문제 유형**
최단 경로
**문제 난이도**
골드5
**접근 방식 및 …
> [김동하-4주차 알고리즘 스터디]

- 김동하/4주차/[백준 11478] 서로 다른 부분 문자열의 개수.java
- 김동하/4주차/[백준 1254] 팰린드롬 만들기.java
- 김동하/4주차/[백준 1865] 웜홀.java
- 김동하/4주차/[백준 19236] 청소년 상어.java
- 김동하/4주차/[백준 5972] 택배 배송.java
* [Baekjoon-13305] 주유소
* [Baekjoon-1931] 회의실 배정
* [Baekjoon-2981] 검문
* [Baekjoon-9020] 골드바흐의 추측
* [Baekjoon-16236] 아기 상어
* [Baekjoon-19236] 청소년 상어
* [Baekjoon-5972] 택배 배송
* [Baekjoon-1865] 웜홀
* [Baekjoon-1254] 팰린드롬 만들기
* [Baekjoon-11478] 서로 다른 부분 문자열의 개수
---------
(n과 홍길동은 본인에 맞게 바꿔주세요! 바꾸시고 이 문장을 지워주세요.)
---
---
**문제 난이도**
**문제 유형**
**접근 방식 및 풀이**
---
**문제 유형**
**접근 방식 및 풀이**
---
**문제 유형**
**접근 방식 및 풀이**
---
**문제 유형**
**접근 방식 및 풀이**
---
**문제 유형**
**접근 방식 및 풀이**
> [김동하-4주차 알고리즘 스터디] (#25)

- 문한결/4주차/서로 다른 부분 문자열의 개수.java
- 문한결/4주차/웜홀.java
- 문한결/4주차/택배 배송.java
- 문한결/4주차/펠린드롬 만들기2.java
---
---
이번주에 면접 준비 때문에 코테 문제를 많이 신경을 못 썼어요 :(
다음주 까지 풀어보도록 하겠습니다!
**문제 난이도**
**문제 유형**
**접근 방식 및 풀이**
---
**문제 난이도**
골드 5
**문제 유형**
최단 경로, 다익스트라
**접근 방식 및 풀이**
한 지점에서 다른 지점으로 갈 수 있는 최소 가중치의 합을 구한다는 점에서 보자마자 다익스트라 알고리즘을 사용했습니다.
다익스트라 알고리즘에서 우선순위 큐로 1에서 갈 수 있는 가중치 중 작은 수를 고른후 해당 위치의 가중치가 이미 작다면, 
continue문을 통해서 넘어가고, 아직 업데이트가 필요하다면, 해당 간선과 연결된 정점으로 이동 후, 정점과 연결된 간선으로 이동합니다. 
그 후 현재 저장된 가중치와 이 간선을 연결시의 cost를 비교해서 이 간선을 연결시의 cost가 작다면 weight배열을 업데이트하고, 다시 que에 넣는 형태로 구현합니다.
---
**문제 난이도**
골드3
**문제 유형**
밸멘포드
**접근 방식 및 풀이**
음의 사이클이 있는지를 찾아야 하므로 Bellmen-ford 알고리즘을 사용했습니다.
해당 문제에서는 시작 정점이 주어지지 않았고, 모든 정점이 연결되어있다는 것이 보장되어있지 않기 때문에, 모든 정점부터 돌면서 알고리즘을 사용해야합니다.
---
**문제 난이도**
실버2
**문제 유형**
부르트포스
**접근 방식 및 풀이**
앞의 문자부터 뒤에서 하나씩 넣어보면서 팰린드롬이 …
> [문한결-4주차 알고리즘 스터디]

- 박예진/5주차/[백준 14620] 꽃길.java
- 박예진/5주차/[백준 15817] 배수 공사.java
- 박예진/5주차/[백준 17485] 진우의 달 여행.java
- 박예진/5주차/[백준 1802] 종이 접기.java
---
---
**문제 난이도**
**문제 유형**
**접근 방식 및 풀이**
---
**문제 난이도**
골드 4
**문제 유형**
dp, 배낭 문제
**접근 방식 및 풀이**
**탑다운** 방식으로 순회를 했다.
그 이유는 중복 계산을 방지하기 위해서다.
만약에 바텀업 방식으로 계산하게 된다면
같은 반복문 내에서 현재 파이프를 고려하는 동안 새로 추가된 값도 즉시 참조될 수 있어서 중복 계산이 발생할 수도 있다.
만약 다음과 같은 예시가 있다면,
N = 1, x = 6
L = [2]
C = [3]  // 길이 2짜리 파이프 3개 사용 가능
이 경우 오름차순(바텀업) 방식을 사용하면
dp[0] = 1 (길이 0을 만드는 방법은 아무것도 사용하지 않는 1가지)
dp[2] += dp[0] → dp[2] = 1
dp[4] += dp[2] → dp[4] = 1 (여기까지는 문제없음)
dp[6] += dp[4] → dp[6] = 1
⚠ 하지만, dp[4]를 dp[2]를 이용해 갱신한 직후에 바로 사용하게 되므로, dp[4]가 1번만 더해진 것이 아니라 2번 이상 더해질 가능성이 생긴다.이 때문에 중복 계산이 발생하여 정답이 잘못될 수 있다. 
다음처럼 탑다운 방식에서는 이전 상태를 기준으로 확장되, 이미 고려한 파이프를 다시 사용하지 않도록 한다.
이 코드에서 j + len * k > x 라면 dp 에 업데이트 하지 않았다. …
> [박예진-5주차 알고리즘 스터디]

- 박준서/5주차/[Baekjoon-14620]꽃길.java
- 박준서/5주차/[Baekjoon-15817]배수공사.java
- 박준서/5주차/[Baekjoon-17485]진우의달여행Large.java
- 박준서/5주차/[Baekjoon-1802]종이접기.java
- 박준서/5주차/[Baekjoon19237]어른상어.java
---
---
**문제 난이도**\
Gold 2
**문제 유형**\
구현
상어의 현재 상태와 상어가 지나온 공간에 남은 냄새를 기록하기 위해 각각 클래스를 만들어 저장\
청소년 상어때와 같이 Call By Reference 문제를 해결하기 위해 임시 저장공간을 할당 받았다
```java
boolean moved = false;
// 1순위: 아무 냄새가 없는 칸으로 이동
for (Integer priority : shark.priority.get(shark.dire)) {
nx = shark.x + dx[priority];
ny = shark.y + dy[priority];
if (nx >= 0 && nx < N && ny >= 0 && ny < N && matrix[ny][nx].smell == 0) {
nd = priority;
moved = true;
break;
}
}
// 2순위: 자신의 냄새가 있는 칸으로 이동
if (!moved) {
for (Integer priority : shark.priority.get(shark.dire)) {
nx = shark.x + dx[priority];
ny = shark.y + dy[priority];
if (nx >= 0 && nx < N && ny >= 0 && ny < N && matrix[ny][nx].smell == i) {
nd = priority;
break;
}
}
}
```
---
배수 공사
**문제 난이도**\
Gold 4
**문제 …
> [박준서-5주차 알고리즘 스터디]

- 김민진/4주차/[Baekjoon-19236] 청소년 상어.java
- 김민진/5주차/[Baekjoon-14620] 꽃길.java
- 김민진/5주차/[Baekjoon-15817] 배수 공사.java
- 김민진/5주차/[Baekjoon-17485] 진우의 달 여행 (Large).java
- 김민진/5주차/[Baekjoon-1802] 종이 접기.java
- 김민진/5주차/[Baekjoon-19237] 어른 상어.java
---
---
**문제 난이도**
골드 2
**문제 유형**
`구현` `시뮬레이션`
**접근 방식 및 풀이**
🦈 상어 정보 저장 클래스
```java
private static class Shark {
int x;
int y;
int dir;
Shark(int x, int y, int dir) {
this.x   = x;
this.y   = y;
this.dir = dir;
}
}
```
📍 해시맵에 `id` 값을 `key`로 해 저장
🧱 2차원 배열의 각 칸에 대한 정보를 저장하는 클래스
```java
private static class Block {
int shark;
int sentOf;
int duration;
Block(int shark, int sentOf, int duration) {
this.shark    = shark;
this.sentOf   = sentOf;
this.duration = duration;
}
}
```
📍 `decreaseDuration()`, `setNewSmell(int id)` 메서드도 함께 정의됨
처음에 상어의 ID를 0부터 시작하도록 설정했다가 꼬여서 1로 시작하게 다시 구현했습니다..
1. 상어 정보 해시 맵 사이즈가 1이면 반복문 종료
2. 아닌 경우 상어를 움직임
- 먼저 빈 공간을 찾고 없는 경우 본인과 같은 냄새가 남은 칸을 선택
- 만약 상어가 존재한다면 삭제(탐색은 ID 오름차순으로 진행하므로 부가적인 처리 불필요)
3. 상어가 모두 …
> [김민진-5주차 알고리즘 스터디]

- 김동하/5주차/[백준 14620] 꽃길.java
- 김동하/5주차/[백준 15817] 배수 공사.java
- 김동하/5주차/[백준 17485] 진우의 달 여행_Large.java
- 김동하/5주차/[백준 1802] 종이 접기.java
- 김동하/5주차/[백준 19237] 어른 상어.java
---
---
**문제 난이도**
골드 2
**문제 유형**
구현
**접근 방식 및 풀이**
이 문제는 그냥 쌩으로 완전탐색을 하면 시간초과가 날 수 밖에 없다고 생각했고, 각각의 격자칸에 해당하는 List 격자칸(3차원 배열),
그리고 각각의 상어에 대해 관리하는 sharks 배열을 두어, 각각의 상어들에 대해 관리를 해줬다.
또한 해당 격자칸의 냄새에 대하 관리하기 위한 smell이라는 2차원 배열을 두어 냄새에 대해 관리해줬다.
1. 순차적으로 상어들이 이동하므로, sharks 배열을 순차 탐색하면서, 해당 Idx의 상어가 살아있다면 이동을 해주는 방법을 사용했다.
-  이동할 때는 상어 배열의 값, 격자 배열의 값 둘 다 바꿔주어야 한다
2. 상어들이 있는 칸에서 번호가 가장 낮은 한마리만 남기고 다 내쫓기 위해서, 격자 list를 정렬하고, 0번 인덱스를 새로운 배열에 담은 후 해당 격자칸이 새로운 배열을 참조하도록 한다. 이때, 남은 idx의 상어들은 상어 배열에서 isAlive 값을 false로 해주어 사망으로 표시한다.
3. 이를 계속 반복하며 1번 상어만 남을 때 까지 하며, 1000회가 넘어가면 break
---
**문제 유형**
DP(배낭)
**문제 난이도**
골드 4
**접근 방식 및 풀이**
해당 길이의 파이프로 만들수 있는 조합을 한 사이클에 돌리며 dp 배열에 표시함
dp[n] = n인 길이를 만들 수 있는 파이프의 경우의 수
1. 3중 반복문을 돌린다. 이떄 인덱스를 …
> [김동하-5주차 알고리즘 스터디]

- 박준서/6주차/[Baekjun-1080]행렬.java
- 박준서/6주차/[Baekjun-1437]수분해.java
- 박준서/6주차/[Baekjun-16472]고냥이.java
- 박준서/6주차/[Baekjun-1717]집합의표현.java
- 박준서/6주차/[Baekjun-20056]마법사상어와파이어볼.java
---
---
**문제 난이도**\
Gold 4
**문제 유형**\
구현
사실 그냥 구현문제.\
어른상어때 처럼 모든 객체가 먼저 움직이고, 처리하는 방식\
메모리가 터지지 않는 범위 내에서 많은 정보를 저장해 처리하는 편이다
```
int nextLocationX = (fb.colunm + dx[fb.direction] * (fb.speed % N) + N) % N;
int nextLocationY = (fb.row + dy[fb.direction] * (fb.speed % N) + N) % N;
```
!! 주의 !!
여기서 `dx[fb.direction] * (fb.speed % N) + N` 이거때문에 오류가 계속 났다\
fb.speed가 N보다 클 수 있다
---
**문제 난이도**\
Silver 1
**문제 유형**\
그리디
뭔가 트리키한 방법을 계속 찾았었는데 결론적으로\
모든 점 matrix[i][j] == 1 에서 flip() 을 계속 해줬다
어짜피 모든 점에서 입력행렬과, 타깃행렬이 같아야 하기 때문에 완탐으로 처리할 수 있음
---
**문제 난이도**\
Gold 4
**문제 유형**\
그리디
왜 풀리는지 이해는 전혀 하지 못했다\
아마도 수학 공식이 있을것으로 예상되지만 저는 그냥\
1~20까지 쪼개는 과정에서 찾은 규칙
1. 무조건 3으로 자르는게 제일 크다
2. 하지만 4일때는 2\*2가 더 큼
3. 따라서 4 초과라면 무조건 3으로 나누고 4 이하에서는 따로 처리
--- …
> [박준서-6주차 알고리즘 스터디]

- 문한결/6주차/고냥이.java
- 문한결/6주차/수분해.java
- 문한결/6주차/집합의표현.java
- 문한결/6주차/파이어볼.java
- 문한결/6주차/행렬.java
---
---
**문제 난이도**
골드4
**문제 유형**
```투포인터```
**접근 방식 및 풀이**
N이 최대 100,000이라 N**2이 되면 안되겠다는 생각을 햇습니다. 또한 연속된 길이의 최댓값을 구하는 문제이므로, 문자열의 시작점과 끝점을 이동시키는 **투포인터**로 접근 했습니다.
end에 있는 문자는현재 집어넣은 문자열인 set과 현재 집어넣은 문자를 key로 하고 갯수를 value로 하는 map에 집어넣고, 
문제에서 요구하는 조건을 넘어갈 때, start를 ++하면서 문자열을 빼가면서 계산했습니다.
```java
public static void findAnswer() {
int start=0;
int end=0;
while(start<=end && end<str.length) {
if(sets.size()<=N) {
answer=Math.max(answer, end-start);
sets.add(str[end]);
if(maps.get(str[end])==null) {
maps.put(str[end],1);
}
else maps.put(str[end], maps.get(str[end])+1);
end+=1;
}
else {
maps.put(str[start],maps.get(str[start])-1);
if(maps.get(str[start])==0) {
sets.remove(str[start]);
maps.remove(str[start]);
}
start+=1;
}
} …
```
> [문한결-6주차 알고리즘 스터디] 

- 김동하/6주차/[백준 1080] 행렬.java
- 김동하/6주차/[백준 1437] 수 분해.java
- 김동하/6주차/[백준 16472] 고냥이.java
- 김동하/6주차/[백준 1717] 집합의 표현.java
- 김동하/6주차/[백준 20056] 마법사상어와파이어볼.java
---
---
**문제 난이도**
골드 4
**문제 유형**
구현
**접근 방식 및 풀이**
이전 문제와 비슷한 결이라고 생각했습니다.
각각의 격자에 흩어져있는 파이어볼을 관리해주는 fires 배열을 두어, 이동시 참조하게 하고 
격자는 각각 List로 두어 여러개의 파이어볼이 들어갈 수 있게 해주었습니다.
1. 파이어볼 이동
1. 기존 데이터를 덮어씌우지 않게 하기 위해 newArr배열 생성 
2. fires 배열을 참조하여 새 격자칸에 이동한 파이어볼 넣기
3. 기존 배열 arr이 newArr을 참조하도록 주입
2. 이동 후
1. fires배열 초기화
2. 각 격자를 탐색하며 해당 격자가 비어있으면 continue
3. size가 1이면 해당 원소를 fires 배열에 추가
4. 여러 파이어볼이 있으면 각각의 파이어볼을 합쳐서 전부 홀수 || 전부 짝수 인지 판단하고 방향을 정함
5. 정해진 방향대로 순차적으로 나누어진 파이어볼을 fires 배열에 추가
---
**문제 유형**
그리디
**접근 방식 및 풀이**
1. 순차적으로 탐색하며 일치하지 않는 칸이 있다면 거기서 reverse 실행
2. reverse는 3X3 격자칸의 원소를 뒤집는  메소드
3. 각 탐색마다 마지막에 모든 원소들이 일치하는지를 확인하는 isSame 메소드를 실행하여 기저조건으로 둠
---
**문제 유형**
그리디
**접근 방식 및 풀이**
이게 그리딘가...?
아무튼 이건 도저히 모르겠어서 찾아봤더니 증명된 이론이 하나 …
> [김동하-6주차 알고리즘 스터디]

- 김민진/6주차/[Baekjoon-1080] 행렬.java
- 김민진/6주차/[Baekjoon-16472] 고냥이.java
- 김민진/6주차/[Baekjoon-1717] 집합의 표현.java
- 김민진/6주차/[Baekjoon-20056] 마법사 상어와 파이어볼.java
- 김민진/6주차/[Baekjun-1437] 수 분해.java
---
---
**문제 난이도**
골드 4
**문제 유형**
`구현` `시뮬레이션`
**접근 방식 및 풀이**
- 사이클 시작 전 배열 초기화(격자 내 파이어볼 전부 비우기)
- 파이어볼만 따로 담아둔 리스트를 돌며 파이어볼 이동
- 파이어볼의 위치를 업데이트 한 후, 해당 격자의 위치에 파이어볼 추가
```Java
int nRow = (fb.row + dx[fb.dir] * mod + N) % N;
int nCol = (fb.col + dy[fb.dir] * mod + N) % N;
/*
a. fb.row + dx[fb.dir] * mod: 현재 행 위치에서 특정 방향으로 속도만큼 이동한 새 위치
b. + N: a에서 음수 값이 나올 수 있는데 이때 바로 % N 연산을 진행하면 음수가 나옴
→ 인덱스 범위가 0 ~ N-1 내에 있도록 보장하기 위한 과정
c. % N: 인덱스 범위가 격자 범위를 벗어나지 않도록 함
*/
```
- 격자를 돌며 파이어볼이 2개 이상인 경우 처리
- 부딪혔을 때의 질량, 속도, 방향을 계산하고 해당 위치의 파이어볼을 업데이트
```java
boolean allSameDir = true;
int firstDirOddEven = board[i][j].get(0).dir % 2;
for (int k = 0; k < board[i][j].size(); k++) {
if ((board[i][j].get(k).dir % 2) != firstDirOddEven) { …
```
> [김민진-6주차 알고리즘 스터디]

- 이종환/6주차/고냥이.java
- 이종환/6주차/수분해.java
- 이종환/6주차/집합의표현.java
- 이종환/6주차/행렬.java
---
---
**문제 난이도**
골드4
**문제 유형**
`구현`, `시뮬레이션`
**접근 방식 및 풀이**
이번주 절반을 아팠어가지고 아직 풀지 못했습니다 ㅠㅠ
다음주에 같이 제출하겠습니다...
---
**문제 난이도**
실버1
**문제 유형**
`그리디`
**접근 방식 및 풀이**
입력되는 두 행렬을 비교하여, 같은 위치에 같은 숫자가 온다면 false, 다르다면 true를 이차원배열 arr에 저장한다.
이후 copy라는 동일한 크기의 boolean 2차원 배열을 만든다.
그 다음은 간단하다. 
그리디하게 copy를 이중 for문을 통해 순회하며, 특정 인덱스의
copy 배열의 값과 arr 배열의 값이 다르다면, 
copy의 그 인덱스 기준 3x3범위를 반대로 뒤집는다.
```java
copy = new boolean[height][width];
for (int i = 0; i < height-2; i++) {
for (int j = 0; j < width-2; j++) {
// 어차피 한번에 3x3을 뒤집기에 이런식으로 범위를 줄여 탐색
if (copy[i][j] != arr[i][j]) {
flip(i,j);
cnt++;
}
}
}
```
이 과정이 다 끝난후, copy와 arr을 비교하여 모든 인덱스에서 값이 동일한지 비교하면 된다.
---
**문제 난이도**
**문제 유형**
`그리디`
**접근 방식 및 풀이**
n이라는 수의 분해 곱의 최댓값이 max[n]일 경우, 
n이 5이상이라는 …
> [이종환-6주차 알고리즘 스터디]

- 박준서/7주차/[Baekjoon-15724]주지수.java
- 박준서/7주차/[Baekjoon-17822]원판돌리기.java
- 박준서/7주차/[Baekjoon-1823]수확.java
- 박준서/7주차/[Baekjoon-20057]마법사상어와토네이도.java
- 박준서/7주차/[Baekjoon-2098]외판원순회.java
- 박준서/7주차/[Baekjun-19585]전설.cpp
---
---
**문제 난이도**\
Gold 3
**문제 유형**\
구현
토네이도의 이동 순서를 따라서 이동위치에 있는 모래량을 분산시키고,\
모든 순회가 끝났을 때 지도에 남아있는 모래의 양을 구하는 문제이다
모래의 양이 % 비율로써 분산되기 때문에 계산에 유의해야 함
토네이도는 같은 길이로 2번 이동하면 길이가 증가\
1 -> 1 -> 2 -> 2 -> 3 -> 3 -> 4
1. dy,dx 배열과 모래의 움직임을 계산하기 위한 sandy,sandx 배열을 만듦\
- 다행히 백트래킹 요소가 없어서 지도는 하나로 진행
2. 토네이도의 이동에 따라 spread() 함수로 모래의 이동 계산
3. 이동 후 남은 모래를 alpha 위치에 둠
---
**문제 난이도**\
Gold 2
**문제 유형**\
구현
맨처음에는 배열을 "돌린다" 에 초점을 두고 풀어서 ArrayDeque로 했다\
하지만 배열은 한칸만 돌리는게 아니라 2차원 배열을 쓰는게 맞다
문제의 요구사항에 맞게 구현하고 원판에서 수 삭제 조건에서\
평균값을 double로 계산해야 하는 것 을 제외하면 나머지는 그냥 쌩 구현
---
**문제 난이도**\
Silver 1
**문제 유형**\
DP
수업시간에 했던 문제와 같아서 빠르게 풀었다
(y1,x1) ~ (y2,x2) 까지의 합 =\
matrix[y2][x2] - matrix[y2][x1 - 1] - matrix[y1 - 1][x2] + matrix[y1 - 1][x1 - 1]
---
**문제 …
> [박준서-7주차 알고리즘 스터디]

- 박예진/7주차/[백준 15724] 주지수.cpp
- 박예진/7주차/[백준 17822] 원판 돌리기.cpp
- 박예진/7주차/[백준 1823] 수확.cpp
- 박예진/7주차/[백준 20057] 마법사 상어와 토네이도.cpp
---
---
**문제 난이도**
골드3
**문제 유형**
구현, 시뮬레이션
**접근 방식 및 풀이**
처음에 문제를 봤을 때 어떻게 돌려야할지 계속 고민했지만
안 돼서 빡구현으로 풀었다. 나중에 구글링을 찾아보니까 다들 빡구현으로 풀었었다..
```cpp
int pdx[4][10] = {
{-2, -1, -1, -1, 0, 1, 1, 1, 2, 0},
{-1, -1, 0, 0, 0, 0, 1, 1, 2, 1},
{-2, -1, -1, -1, 0, 1, 1, 1, 2, 0},
{-2, -1, -1, 0, 0, 0, 0, 1, 1, -1}
};
int pdy[4][10] = {
{0, -1, 0, 1, -2, -1, 0, 1, 0, -1},
{-1, 1, -2, -1, 1, 2, -1, 1, 0, 0},
{0, -1, 0, 1, 2, -1, 0, 1, 0, 1},
{0, -1, 1, -2, -1, 1, 2, -1, 1, 0}
};
```
다만, 한가지 아쉬운 점은 percent까지 배열에 넣어서 푼 점이다.
나중에 풀 땐, 1차원 배열에 idx 접근을 다르게 하는 방식으로 풀어봐야겠다.
```cpp
int percent[4][9] = {
{2, 10, 7, 1, 5, 10, 7, 1, 2},
{1, 1, 2, 7, 7, 2, 10, 10, 5},
{2, 1, 7, 10, 5, 1, 7, 10, 2},
{5, 10, 10, 2, 7, 7, 2, 1, 1}
};
```
---
**문제 난이도**
골드2 …
> [박예진-7주차 알고리즘 스터디]

- 김민진/7주차/[Baekjoon-15724] 주지수.java
- 김민진/7주차/[Baekjoon-17822] 원판 돌리기.java
- 김민진/7주차/[Baekjoon-1823] 수확.java
- 김민진/7주차/[Baekjoon-2098] 외판원 순회.java
---
---
**문제 난이도**
골드 3
**문제 유형**
`구현` `시뮬레이션`
**접근 방식 및 풀이**
어제 저녁부터 급격하게 몸 상태가 안좋아져서 못 풀었습니당...
내일 풀게요..ㅜ
---
**문제 난이도**
골드 2
**문제 유형**
`구현` `시뮬레이션`
**접근 방식 및 풀이**
너무힘들었어요
1. 원판 돌리기
2. 사방 확인하여 중복 숫자 제거하기
3. 숫자가 제거되지 않은 경우 값 업데이트
📍 `idx` 배열
: 12시 방향에 있는 숫자의 인덱스 저장
: 모듈러 연산을 통해 위치를 옮김
&nbsp;&nbsp;&nbsp;&nbsp;→ 반시계방향인 경우 음수가 나올 수 있으므로 모듈러 연산 전 `+ M` 진행 
```java
private static int[]   idx;
for (int i = x - 1; i < N; i += x) {
int toMove = k * (d == 0 ? CLOCKWISE : CCLOCKWISE);
idx[i] = (idx[i] + M + toMove) % M;
}
```
📍 사방 확인 코드
: `toRemove`는 `Set`
```java
for (int d = -1; d <= 1; d += 2) {
// horizontal
adj = (targetJ + M + d) % M;
if (discs[disc][adj] == target) {
toRemove.add(new Point(disc, adj));
toRemove.add(new Point(disc, …
```
> [김민진-7주차 알고리즘 스터디]

- 이종환/6주차/고냥이.java
- 이종환/6주차/수분해.java
- 이종환/6주차/집합의표현.java
- 이종환/6주차/행렬.java
- 이종환/7주차/마법사상어와_토네이도.java
- 이종환/7주차/수확.java
- 이종환/7주차/외판원순회.java
- 이종환/7주차/원판돌리기.java
- 이종환/7주차/주지수.java
---
---
**문제 난이도**
골드3
**문제 유형**
`구현`,`시뮬레이션`
**접근 방식 및 풀이**
결국 구현문제이기 때문에,  구현 부분별로 나눈 후, 각각 구현하여 합쳤다.
`processSandMove()` 라는 모래 한칸에 대한 메서드를 이용하는 `processSideAll` 등 다른 메서드들을 통해  모래가 퍼지는 과정을 구현하였다. 
이때 각각의 방향에 대해 전부 예외처리를 하기 보다는 어느 방향을 보고 있느냐가 설정되면 그에 맞춰서 진행이 될 수 있도록 구상하였다.
```java
private static void move(int y,int x ) { // 토네이도가 도착하는 곳의 좌표
//다른 곳으로 다 날린 후 남아있는 녀석. 이는 나중에 alpha로 이동한다.
originalAmount = arr[y][x]; //원래 양
int leftAmount = arr[y][x];
int right = (front+3)%4; // 가는 방향의 오른쪽 방향을 나타내는 인덱스
int left = (front+1)%4; // 가는 방향의 왼쪽 방향을 나타내는 인덱스
side = left; // 목표 방향(왼 )
leftAmount -= processSideAll(y,x);
side = right; // 목표 방향(오)
leftAmount -= processSideAll(y,x);
//정면
leftAmount -= processSandMove(y,x,5,2,0);
// 남은거 alpha로 …
```
> [이종환-7주차 알고리즘 스터디]

- 문한결/7주차/수확.java
- 문한결/7주차/원판돌리기.java
- 문한결/7주차/주지수.java
- 문한결/7주차/토네이도.java
---
외판원 순회는 다음주 까지 풀어볼게여.. 이번주에 토익스피킹이랑 sqld땜시..
---
**문제 난이도**: 골드3  
**문제 유형**: ```구현```  
**접근 방식 및 풀이**
- 격자 내에서 토네이도를 이동시키면서 모래를 퍼뜨리는 문제입니다.
- ```토네이도```가 이동하면서 특정 비율로 모래를 이동시키는 방식이 중요합니다.
- 각 방향별 ```dx, dy```를 설정하여 방향을 전환하면서 모래를 이동시켰습니다.
- ```inBounds``` 함수를 이용하여 배열을 벗어나지 않도록 처리하였습니다.
---
**문제 난이도**: 골드2
**문제 유형**: ```구현```  
**접근 방식 및 풀이**
- 원판을 회전시키고, 같은 숫자가 인접한 경우를 제거하는 문제입니다.
- ```Queue```를 사용하여 BFS 방식으로 인접 숫자 탐색을 수행하였습니다.
- 만약 인접한 수가 없는 경우에는 평균값을 기준으로 값을 변경하는 방식으로 구현하였습니다.
---
**문제 난이도**: 실버1  
**문제 유형**: ```누적합```  
**접근 방식 및 풀이**
- ```누적합```을 사용하여 특정 구간의 값을 빠르게 구하는 문제입니다.
- ```dp[i][j]```를 사용하여 1,1부터 i,j까지의 사각형 합을 미리 계산하였습니다.
- 이후 쿼리가 들어올 때 ```dp```를 이용하여 O(1) 시간에 답을 구할 수 있도록 처리하였습니다.
---
**문제 난이도**: 골드3
**문제 유형**: …
> [문한결-7주차 알고리즘 스터디] 

- 김동하/7주차/[백준 15724] 주지수.java
- 김동하/7주차/[백준 17822] 원판돌리기 .java
- 김동하/7주차/[백준 1823] 수확.java
- 김동하/7주차/[백준 20057] 마법사상어와토네이도.java
- 김동하/7주차/[백준 2098] 외판원 순회.java
(n과 홍길동은 본인에 맞게 바꿔주세요! 바꾸시고 이 문장을 지워주세요.)
---
---
**문제 난이도**
골드 3
**문제 유형**
구현
**접근 방식 및 풀이**
- 방향에 따라 dx, dy토네이도에 대한 dx dy값이 달라지므로 각각의 방향에 대한 정보를 2차원 배열을 활용하여 정리해둔다.
그리고 각 배열의 idx별로 첫번째, 두번째는 10%가 적용될 격자, 네번째, 다섯번째는 7%가 적용될 격자로 이동하는 식으로 정렬해둔다.
``` java 
public static int ddx[][] = {
{-1,1,0,-1,1,-2,2,-1,1},
{1,1,2,0,0,0,0,-1,-1},
{-1,1,0,-1,1,-2,2,-1,1},
{-1,-1,-2,0,0,0,0,1,1}
};
public static int ddy[][] = {
{-1,-1,-2,0,0,0,0,1,1},
{-1,1,0,-1,1,-2,2,-1,1},
{1,1,2,0,0,0,0,-1,-1},
{-1,1,0,-1,1,-2,2,-1,1}
};
public static int[] perc = {10,10,5,7,7,2,2,1,1};
- 이후 달팽이 그리기에서 하듯이 토네이도를 움직이며 움직인 방향에 따른 격자칸으로 모래를 흩날린다.
- 모래를 흩날릴 때는 흩날릴 격자칸의 모래를 저장해두고, 각각의 칸마다 흩날려진 모래를 비율과 함께 계산한 후 각 격자에 …
```
> [김동하-7주차 알고리즘 스터디]

- 김민진/7주차/[20057] 마법사 상어와 토네이도.java
- 김민진/8주차/[Baekjoon-15787] 기차가 어둠을 헤치고 은하수를.java
- 김민진/8주차/[Baekjoon-20055] 컨베이어 벨트 위의 로봇.java
- 김민진/8주차/[Baekjoon-20058] 마법사 상어와 파이어스톰.java
- 김민진/8주차/[Baekjoon-2151] 거울 설치.java
- 김민진/8주차/[Baekjoon-28075] 스파이.java
---
---
**문제 난이도**
골드 3
**문제 유형**
`구현` `시뮬레이션` `BFS`
**접근 방식 및 풀이**
1. `rotate()`: 부분배열을 회전하는 함수
부분 배열을 여러개 만들기 싫어 입력받은 배열과 같은 크기의 `copy` 배열을 생성하여 배열 전체의 변경 내역을 저장한 후 한꺼번에 기존 배열을 업데이트함
인덱스 처리가 까다로워서 시간이 좀 걸렸습니다..
```java
for (int a = 0; a < len; a += pow) {
for (int b = 0; b < len; b += pow) {
// make copy
for (int i = 0; i < pow; i++) {
for (int j = 0; j < pow; j++) {
// rotate
copy[a + j][b + pow - i - 1] = matrix[a + i][b + j];
}
}
}
}
```
📍 `a`, `b`: 부분 배열의 크기에 맞춰 건너뛰기
&nbsp;&nbsp;&nbsp;&nbsp;→ 부분 배열의 시작점을 가리킴
📍 `i`, `j`: 부분 배열 내의 인덱스
2. `meltIce()`: 얼음을 녹이는 함수
업데이트를 하면서 반복을 진행하는 경우 다음 값에 업데이트된 값이 영향을 줄 수 있기 때문에 변경된 값의 위치를 `toDecreas` 리스트에 넣어 모든 좌표의 확인이 끝난 후 업데이트
```java
private static void meltIce() {
toDecrease.clear(); …
```
> [김민진-8주차 알고리즘 스터디]

- 문한결/7주차/외판원.java
- 문한결/8주차/거울설치.java
- 문한결/8주차/스파이.java
- 문한결/8주차/은하수.java
- 문한결/8주차/컨베이어.java
- 문한결/8주차/파이어스톰.java
---
---
**문제 난이도**
골드3
**문제 유형**
```구현```
**접근 방식 및 풀이**
구현자체는 어렵지 않으나 문제를 잘읽어야하는 문제라고 생각합니다.
저는 L1,L2가 연속된 동작이 아니라, 각각의 단계가 따로따로 개별로써 존재하는 줄 알고 풀어서 시간을 좀 잡아먹었습니다.
수행받으라고 지시받은 단계동안 회전하고, 얼음을 제거하면 됩니다.
회전하는 함수는 전체를 회전하는 ```rotateall```, 각 하나의 격자동안 회전하는 ```rotate```, ```rotate```함수내에서 얼음을 옮기는 ```moveIce```로 나누어서, 각 메서드마다 책임을 나누어서 코드를 짜기 편하기 하였습니다. 
얼음 제거는 그냥 돌면서 인접한 얼음을 확인하는 방식으로 짰습니다.
---
**문제 난이도**
실버2
**문제 유형**
```비트마스킹```
**접근 방식 및 풀이**
비트 마스킹의 정석과도 같은 문제라고 생각합니다.
탑승했을 때는 해당자리에 탑승했을 때의 수와 or연산을 하고, 하차할 때는 해당 자리를 비워뒀을 때 And연산을 합니다.
command로 3이 들어왔을 때는 <<를 4가들어왔을 때는 >>를 이용해서 해결하면 됩니다.
---
**문제 난이도**
골드5
**문제 유형**
```구현```
**접근 방식 및 풀이**
문제의 내린다를 컨베이어의 내린다로 잘못읽어서 시간을 진짜 많이 잡아 먹은 문제.
각 컨베이어는 배열로, 로봇은 list로 짜서, 문제에서 하라고한 회전과 로봇 …
> [문한결-8주차 알고리즘 스터디]

- 박준서/8주차/[Baekjoon-15787]기차가어둠을헤치고은하수를.java
- 박준서/8주차/[Baekjoon-20055]컨베이어벨트위의로봇.java
- 박준서/8주차/[Baekjoon-20058]마법사상어와파이어스톰.java
- 박준서/8주차/[Baekjoon-2151].거울설치.java
- 박준서/8주차/[Baekjoon-28075]스파이.java
---
---
**문제 난이도**\
Gold 3
**문제 유형**\
구현
한국어 같지 않은 문제, 비루한 설명\
문제 설명을 잘 보도록 하자.
구현 자체는 어렵지 않았다\
돌리고, 녹이고가 끝
!! 주의 !!\
출력값 조건을 잘 봐야 한다
---
**문제 난이도**\
Gold 5
**문제 유형**\
구현
구현중에 쉬운 문제에 속한 것 같다\
문제 설명도 깔끔하고 배열 순서만 잘 고려한다면 금방 풀 수 있다
---
**문제 난이도**\
Silver 2
**문제 유형**\
비트마스킹, Set
주어진 4가지 명령에 따라 20 자리 비트를 추가 & 삭제 하면 됨
shift 연산 시 남는 비트를 지워줘야 정답이 나옴
---
**문제 난이도**\
Gold 3
**문제 유형**\
최단거리, 다익스트라
무지성 dfs로 사이클만 피하면서 구현하다가 메모리 초과가 계속 났다\
아마 모든 사이클 케이스를 잡지 못한 것 같다
다시 다익스트라를 활용해서 우선순위 큐에 현재 cost가 작은 순서대로 진행하면\
모든 케이스를 돌지 않고 중간에 도착하게 된다
ex) 3hop에서 도착하지 못하고 4hop에서 도착했다면 4 미만의 최단거리는 나올 수 없다
---
**문제 난이도**\
Silver 3
**문제 유형**\
dfs, 브루트포스
dfs로 모든 케이스를 돌며 이전 위치와 같을 때 처리만 해주면 된다
---
> [박준서-8주차 알고리즘 스터디]

- 박예진/9주차/[백준 1389] 케빈 베이컨의 6단계 법칙.cpp
- 박예진/9주차/[백준 21610] 마법사 상어와 비바라기.cpp
- 박예진/9주차/[백준 2531] 회전초밥.cpp
- 박예진/9주차/[백준 2637] 장난감 조립.cpp
- 박예진/9주차/[백준 5052] 전화번호 목록.cpp
---
---
**문제 난이도**
골드5
**문제 유형**
구현, 시뮬레이션
**접근 방식 및 풀이**
구현 문제이다. 문제를 잘 읽고 그대로 하면 풀 수 있는 문제이다. 
모든 격자판이 연결된 문제이기 때문에
구름이 d 방향으로 s칸 이동할 때
이동하는 부분을 잘 지정해주는 게 핵심 포인트이다.
```cpp
int nx = (now.x + dx[d - 1] * (s % N) + N) % N;
int ny = (now.y + dy[d - 1] * (s % N) + N) % N;
```
이 부분을 처음에 구현할 때 음수 나오면 abs를 해줬었는데
abs()를 사용하면 mod 연산이 왜곡될 수 있으므로 + N % N 방식으로 변경해야 한다고 한다.
---
**문제 난이도**
골드2
**문제 유형**
위상정렬, dp
**접근 방식 및 풀이**
처음에는 단순 위상정렬로 풀었다.
진입차수가 0일 때를 기본 부품이라고 생각하고 queue에 다음 노드와 가중치들의 곱들을 넣어줬었다.
그러나 이렇게 풀 경우 불필요한 과정이 계속해서 반복돼서 **메모리 초과**라는 결과가 떴다.
<메모리 초과 코드>
```cpp
int topology(int start) {
int answer = 0;
queue <pair <int, int>> q; // 다음과 가중치
q.push({ start, 1 });
int num = 1;
while (!q.empty()) {
int now = q.front().first;
int cost …
```
> [박예진-9주차 알고리즘 스터디]

- 박준서/9주차/[Baekjoon-10999]구간합구하기2.java
- 박준서/9주차/[Baekjoon-1389]케빈베이컨의6단계법칙.java
- 박준서/9주차/[Baekjoon-21610]마법사상어와비바라기.java
- 박준서/9주차/[Baekjoon-2531]회전초밥.java
- 박준서/9주차/[Baekjoon-2637]장난감조립.java
- 박준서/9주차/[Baekjoon-5052]전화번호목록.java
---
---
**문제 난이도**\
Gold 5
**문제 유형**\
구현
구현 너무 어려워용
- moveClouds(d, s)\
모든 구름을 d 방향으로 s칸 이동\
격자는 원형으로 연결되어 있어 경계를 넘어가면 반대편으로 이동
- rain()\
구름이 있는 칸의 물의 양을 1 증가
- copyWater()\
물이 증가한 칸에 대해 대각선 방향에 물이 있는 바구니 수만큼 물의 양을 증가\
이때 경계를 벗어나는 칸은 대각선 방향 계산에서 제외
- createClouds()\
물의 양이 2 이상인 모든 칸에 구름이 생기고, 물의 양이 2 감소\
!! 이전에 구름이 있던 칸은 제외 !!
- isCloud(x, y)\
주어진 좌표에 구름이 있는지 확인
- countMatrix()\
모든 칸의 물의 양을 합산하여 반환
---
**문제 난이도**\
Gold 2
**문제 유형**\
위상 정렬
1. 각 부품 간의 관계를 graph 배열에 저장\
동시에 각 부품의 진입 차수를 pointed 배열에 계산
2. 완제품인 N번 부품부터 시작 (큐에 N 추가)\
material[N] = 1로 설정 (완제품은 1개 필요)
3. 위상 정렬 수행\
큐가 빌 때까지 반복:\
현재 부품 now를 큐에서 꺼냄\
현재 부품을 만드는 데 필요한 다른 부품들을 확인\
i의 진입 차수를 감소시키고, 0이 되면 큐에 추가\
현재 부품이 중간 부품이면 material[now] = 0으로 설정 (기본 부품이 아님)
---
**문제 난이도**\ …
> [박준서-9주차 알고리즘스터디] 

- 이종환/9주차/마법사상어와_비바라기.java
- 이종환/9주차/장난감조립.java
- 이종환/9주차/전화번호목록.java
- 이종환/9주차/케빈베이컨의_6단계법칙.java
- 이종환/9주차/회전초밥.java
---
---
**문제 난이도**
`골드5`
**문제 유형**
`구현`
**접근 방식 및 풀이**
구현 문제이기에 우선 메소드를 어떻게 구현할 지 구상부터 하였다.
- 구름의 이동 및 그로 인한 물 증가(`move()`)
- 물복사 버그 (`duplicate()`)
- 구름 생성(`createCloud()`)
-
이렇게 세 가지로 메인 로직을 나눠서 구현하였다. 
이때 1번과 N번 열/행이 연결되어있는것을 고려하여서 코드를 작성하였다.
또한 이전에 구름이 있던 곳에는 구름이 생기면 안된다는 조건을 위하여
`createCloud()` 내부에 `preCloud[]`라는 배열을 통하여 이전에 구름이 있던 위치를 기록하였다.
```java
private static void createCloud() {
//이전에 구름이 있던 곳 == 증가한 곳 -> 여기는 visited 처리
boolean[][] preCloud = new boolean[size][size];
for (Point t: increased) preCloud[t.y][t.x] = true;
for (int i = 0; i < size; i++) {
for (int j = 0; j < size; j++) {
if (preCloud[i][j] || arr[i][j] < 2) continue;
arr[i][j] -=2;
clouds.add(new Point(j,i));
} …
```
> [이종환-9주차 알고리즘스터디]

- 박준서/10주차/[Baekjoon-10815]숫자카드.java
- 박준서/10주차/[Baekjoon-11000]강의실배정.java
- 박준서/10주차/[Baekjoon-14391]종이조각.java
- 박준서/10주차/[Baekjoon-2143]두배열의합.java
- 박준서/10주차/[Baekjoon-21611]마법사상어와블리자드.java
---
---
**문제 난이도**\
Gold 1
**문제 유형**\
구현
구현 너무 어려워용
구슬의 수는 N*N-1개 이므로 ArrayList<> .size() == N*N-2 개 임을 주의해야 함
- blizzard()\
블리자드 마법으로 구슬 제거
- repeatExplode()\
연속으로 폭발이 일어나지 않을 때까지 반복
- explodeMarbles()\
구슬 폭발 처리 (연속된 4개 이상의 같은 구슬 폭발)
- makeMarbles()\
구슬 변화 처리 (연속된 구슬을 개수, 번호 쌍으로 변경)
- directionForSeq()\
나선형 이동을 위한 방향 전환 메소드
---
**문제 난이도**\
Silver 5
**문제 유형**\
이분 탐색
수의 범위는 커서 배열로는 못풀고 동적으로 받아서 정렬 후 이분탐색하는 문제인 것 같다
하지만 set을 이용하면 쉽게 풀린다\
모든 입력을 set에 넣어두고 존재한다면 1 아니면 0
---
**문제 난이도**\
Gold 3
**문제 유형**\
이분 탐색
수의 범위가 -10억 ~ 10억이고, n이 1000이라 배열로 풀수는 없다\
처음에는 투포인터로 풀려 했지만 로직이 복잡해질 것 같아서\
모든 경우의수 n(n+1)/2를 TreeMap에 모두 저장했다
이후 첫 배열의 키 값을 반복자로 삼아 map1[it] \* map2[T-it]을 모두 더해주면 됨
---
**문제 난이도**\
Gold 3
**문제 유형**\
DFS
16개의 지점에서 최적 값을 찾는거라 …
> [박준서-10주차 알고리즘 스터디]

- 이종환/10주차/강의실배정.java
- 이종환/10주차/두배열의합.java
- 이종환/10주차/마법사_상어와_블리자드.java
- 이종환/10주차/숫자카드.java
- 이종환/10주차/종이조각.java
(n과 홍길동은 본인에 맞게 바꿔주세요! 바꾸시고 이 문장을 지워주세요.)
---
---
**문제 난이도**
골드1
**문제 유형**
`구현` `시뮬레이션`
**접근 방식 및 풀이**
여태까지 스터디에서 나온 구현 문제 중 가장 풀이가 긴 편에 속하는 문제였다.
그렇기에 처음부터 최대한 메서드를 분리하여 접근하였다.
얼음파편에 의해 삭제되는 것을 `breakBeads()`, 모든 구슬의 움직임은 `moveBeads()`, 연속된 구슬이 폭발하는 것은 `explode()`, 그리고 이후의 구슬 변환 과정은 `duplicate()`를 통해 구현하였다.
```java
private static void process() throws IOException {
for (int i = 0; i < magicCnt; i++) {
StringTokenizer st = new StringTokenizer(br.readLine());
int direction = convertDir[Integer.parseInt(st.nextToken())];
int len = Integer.parseInt(st.nextToken());
breakBeads(direction,len);
moveBeads();
while(explode() != 0) {
moveBeads();
}
duplicate();
}
```
이때 폭발 후 이동은 폭발한 위치의 값을 0으로 …
> [이종환-10주차 알고리즘 스터디]

- 김동하/10주차/[백준 10815] 숫자 카드.java
- 김동하/10주차/[백준 11000] 강의실 배정.java
- 김동하/10주차/[백준 14391] 종이 조각.java
- 김동하/10주차/[백준 2143] 두 배열의 합.java
- 김동하/10주차/[백준 21611] 마법사 상어와 블리자드.java
---
---
**문제 난이도**
골드 1
**문제 유형**
구현
**접근 방식 및 풀이**
달팽이 문제였지만, 바로 옆으로 이동하는 것이 아닌 0이 아닌것이 나올 때 까지 작업해줘야 하는 상황이었어서 인덱스 다루기가 살짝 어려웠다.
그래서 떠오른 생각은 메소드를 분리시킨 후 기존 메서드에서 탐색을 하다가 0이 아닌 값까지 탐색을 해줘야 하는 부분이 있으면 분리시킨 메서드에 파라미터를 통해 현재까지 인덱스작업을 한 정보들을 전부 넘겨주고, 넘겨받은 파라미터를 통해 다시 작업을 한다는 개념으로 접근했다.
```java
public static Node findNextNotZero(int x, int y, int moveCnt, int siz, int dir, int changeDirCnt) {
if(arr[x][y] != 0) return new Node(x,y);
while(siz < n) {
x = x + dx[dir];
y = y + dy[dir];
moveCnt++;
if(moveCnt == siz) {
dir = changeDir(dir);
changeDirCnt++;
moveCnt = 0;
}
if(changeDirCnt == 2) {
siz++;
changeDirCnt = 0;
}
if(arr[x][y] != 0) return new Node(x,y);
}
for(int i = 0; i < n; i++) {
x = x + dx[dir];
y = y + dy[dir]; …
```
> [김동하-10주차 알고리즘 스터디]

- 박준서/11주차/[Baekjoon-1562]계단수.java
- 박준서/11주차/[Baekjoon-17490]일감호에다리놓기.java
- 박준서/11주차/[Baekjoon-23290]마법사상어와복제.java
- 박준서/11주차/[Baekjoon-2352]반도체설계.java
- 박준서/11주차/[Baekjoon-24526]전화돌리기.java
---
---
**문제 난이도**\
Gold 1
**문제 유형**\
구현
물고기와 상어의 이동이 다른데 한 배열 dx,dy로 하기 위해 시간을 더 썼다\
급할때는 그냥 각각 따로 만드는 편이 좋아 보인다
1. 물고기에게 복제 마법 시전
- duplicationCasting()
- 새 Fish 배열을 만들어서 깊은복사
2. 물고기의 이동
- moveFishes()
3. 상어의 이동
- moveShark(), eat()
- 백트래킹으로 최대한 많은 물고기를 먹고, 기준에 맞춰(상,좌,하,우) 가장 빠른 값으로 길을 정함
4. 상어가 먹고 남은 자리 변경
- removeSmells()
- 물고기를 먹은 자리만 3으로 남겨놔야 함
5. 복제 마법 완료
- duplication()
---
**문제 난이도**\
Gold 2
**문제 유형**\
LIS, 이분탐색
구체적인 문제의 설명만 다르고 LIS와 똑같다\
증가하는 부분 수열의 최대 크기를 구하는 것
새로운 값이 들어왔을 때 기존 수열에 새 값을 넣어준다\
input=1 : 1\
input=2 : 1 2\
input=5 : 1 2 5\
input=6 : 1 2 5 6\
input=4 : 1 2 4 6
가장 긴 수열은 계속 유지되고 중간값만 바뀌기 때문에 배열의 크기가 답
---
**문제 난이도**\
Gold 1
**문제 유형**\
DP, Bitmasking
일반 계단 수를 풀었다면 접근은 쉽게 할 수 있다\
하지만 DP에 Bitmasking이 들어가서 구현에 …
> [박준서-11주차 알고리즘 스터디]

- 김민진/11주차/[Beakjoon-1562] 계단 수.java
- 김민진/11주차/[Beakjoon-17490] 일감호에 다리 놓기.java
- 김민진/11주차/[Beakjoon-23290] 마법사 상어와 복제.java
- 김민진/11주차/[Beakjoon-2352] 반도체 설계.java
- 김민진/11주차/[Beakjoon-24526] 전화 돌리기.java
---
---
**문제 난이도**
골드 1
**문제 유형**
`구현` `시뮬레이션`
**접근 방식 및 풀이**
이제 상어 더 안 한대서 좋아했는데 더 한 걸 할 예정이라면서요..?
🖨️ `copyFishInfo()`
이전 물고기 정보를 저장하는 List를 초기화하고 사이클이 끝난 후의 물고기 정보를 저장하는 함수
`fishCur`는 `fishPrev`를 기반으로 업데이트하기 때문에 `fishCur` 또한 초기화 필요
🐠 `moveFish()`
`fishPrev`를 기반으로 물고기를 이동시키는 함수
```java
// ←, ↖, ↑, ↗, ↘, ↓, ↙
private static final int[] dx = { 0, -1, -1, -1, 0, 1, 1, 1 };
private static final int[] dy = { -1, -1, 0, 1, 1, 1, 0, -1 };
```
반시계방향 회전이므로 `- 1 % 8` 연산이 필요하나 음수 값이 나올 수 있으므로 `+ 8 % 8` 진행
→ 현재 물고기의 위치를 기반으로 8부터 1까지 내림차순으로 더해서 모듈러 연산을 진행하는 경우 반시계방향 회전 구현 가능
```java
for (int fish : fishPrev[i][j]) {
boolean moved = false;
for (int k = 8; k > 0; k--) {
int d = (fish + k) % 8;
...
```
1. 격자를 벗어나거나, 물고기의 냄새가 남아있거나, 상어의 위치인 …
> [김민진-11주차 알고리즘 스터디]

- 문한결/11주차/계단수.java
- 문한결/11주차/반도체.java
- 문한결/11주차/상어.java
- 문한결/11주차/일감호.java
- 문한결/11주차/전화돌리기.java
---
---
**문제 난이도**
Gold 1
**문제 유형**
구현
다음과 같은 흐름으로 메서드를 진행합니다.
1. 초기화 (init())
입력을 받아 초기 상태를 설정합니다.
물고기 정보, 상어 위치, 냄새 배열, 블록 배열 초기화.
2. 시뮬레이션 루프 (execute())
총 s 번 반복합니다.
매 턴마다 다음과 같은 순서로 동작합니다.
3. 복제 마법 준비 (commandCopyFishes())
현재 상태의 물고기 정보를 복사하여 임시 저장합니다.
복제는 이후에 수행하므로 임시로 저장만 합니다.
4. 물고기 이동 (moveFish())
모든 물고기를 8방향으로 이동시키고, 상어는 DFS로 3칸 경로를 탐색하여 사전 순 경로로 이동하면서 물고기를 제거하고 냄새를 남기며 위치를 갱신합니다.
5. 냄새 감소 (reduceSmell())
냄새를 한 턴 감소시킵니다.
냄새는 -3 으로 시작하여 0이 되면 사라집니다.
6. 복제 마법 완료 (executeCopyFishes())
임시로 저장해 둔 물고기 복제를 수행하여 원래 배열에 복제합니다.
---
**문제 난이도**\
Gold 2
**문제 유형**
LIS, 이분탐색
해당 문제에서는 TreeSet을 통해서 LIS를 구현했습니다.
```java
static void execute(){
for (int i = 0; i < n; i++) {
Integer ceiling = sets.ceiling(arr[i]);
if (ceiling != null) { …
```
> [문한결-11주차 알고리즘 스터디]

- 이종환/11주차/계단수.java
- 이종환/11주차/마법사상어와_복제.java
- 이종환/11주차/반도체설계.java
- 이종환/11주차/일감호에_다리놓기.java
- 이종환/11주차/전화돌리기.java
---
---
**문제 난이도**
골드1
**문제 유형**
`구현` `시뮬레이션`
**접근 방식 및 풀이**
전통의 시뮬레이션 시리즈-상어의 중 한문제이다. 
사실 여태까지 상어 시리즈를 많이 진행하였기에 로직 구현 자체에 오래걸리지는 않았다.
다만 평소에 row를 y, col을 x로 설정해서 풀었는데, 이 문제에서는 반대로 제시되어있어서 그 부분에서 시간을 많이 소비하였다.  
전반적으로 이동을 할 때, 바로 이동시키기 보다는 큐에 넣어놨다가, 로직 단위로 한 번에 이동시키는 전략을 구사하였다.
```java
private static void copyFish() {
for (int i = 0; i < 4; i++) {
for (int j = 0; j < 4; j++) {
ArrayList<Fish> block = sea.get(i).get(j);
for (Fish f: block) exRound.add(f);
}
}
}
private static void moveFishes() {
for (int i = 0; i < 4; i++) {
for (int j = 0; j < 4; j++) {
ArrayList<Fish> block = sea.get(i).get(j);
for (Fish f: block) {
movementResult.add(moveFish(f));
}
block.clear();
}
}
while(!movementResult.isEmpty()) {
Fish f = …
```
> [이종환-11주차 알고리즘 스터디]

- 박예진/12주차/[백준 17144] 미세먼지 안녕!.cpp
- 박예진/12주차/[백준 21924] 도시 건설.cpp
- 박예진/12주차/[백준 7511] 소셜 네트워킹 어플리케이션.cpp
---
---
**문제 난이도**\
Gold 4
**문제 유형**\
구현
---
**문제 난이도**\
Gold 1
**문제 유형**\
DP
---
**문제 난이도**\
Gold 4
**문제 유형**\
수학
---
**문제 난이도**\
Gold 4
**문제 유형**\
MST
---
**문제 난이도**\
Gold 4
**문제 유형**\
union find
---
> [박예진-12주차 알고리즘 스터디]

- 박준서/12주차/[Baekjoon-1311]할일정하기1.java
- 박준서/12주차/[Baekjoon-17144]미세먼지안녕!.java
- 박준서/12주차/[Baekjoon-21924]도시건설.java
- 박준서/12주차/[Baekjoon-2405]세수,두M.java
- 박준서/12주차/[Baekjoon-7511]소셜네트워킹애플리케이션.java
---
---
**문제 난이도**\
Gold 4
**문제 유형**\
구현
cnt : 방 안의 미세먼지 총량\
robot : 공기청정기의 위치(상단, 하단)\
matrix : 방의 상태를 나타내는 2차원 배열
spread()\
미세먼지는 인접한 네 방향으로 확산\
각 칸의 미세먼지 양의 5분의 1이 인접한 칸으로 확산\
확산은 모든 칸에서 동시에 일어나므로 임시 배열을 사용
conditioner()\
공기청정기는 바람을 순환시켜 미세먼지를 이동\
상단 공기청정기는 반시계 방향, 하단 공기청정기는 시계 방향으로 순환
---
**문제 난이도**\
Gold 1
**문제 유형**\
DP
외판원 문제와 동일하다\
N개의 사람과 N개의 일이 주어지고 가장 작은 값을 구하는 것
외판원 문제 개념을 알고 있다면 쉽게 해결할 수 있다
---
**문제 난이도**\
Gold 4
**문제 유형**\
수학
어떤 세 수를 정해서 평균값과 중앙값이 멀어지게 하려면\
한 쪽은 최대한 작고, 한 쪽은 최대한 멀어져야 함
1,2,3,4 ... 10 일 때 현재 값이 4라면\
3,4,10 or 1,4,5 가 후보가 되는 것
---
**문제 난이도**\
Gold 4
**문제 유형**\
MST
크루스칼로 플어 봤다\
모든 간선을 graph 배열에 저장하고 비용기준 오름차순 정렬
그 후에 union find로 모든 정점을 연결해 주면서 최단거리를 알아냄\
-> 미리 저장해 둔 모든 간선 합에서 최단거리를 빼주면 답
---
**문제 …
> [박준서-12주차 알고리즘 스터디]

- 문한결/12주차/도시건설.java
- 문한결/12주차/세수두M.java
- 문한결/12주차/소셜네트워크.java
- 문한결/12주차/할일정하기.java
---
- [] **문제 1: 미세먼지 안녕!**
미세먼지 안녕은 다음주까지 풀어보겠습니당...(이번주 면접 이슈로 많이 문제를 못 풀었네요 ㅠ)
---
**문제 난이도**\
Gold 4
**문제 유형**\
구현
---
**문제 난이도**\
Gold 1
**문제 유형**\
DP
- 비트마스크 DP 를 사용.
- 사람 번호 (1 ~ N) 순서대로 순회하면서, 이미 할당된 일을 비트마스크로 관리.
- dp[i][mask]: i번째 사람까지 고려했을 때, mask 상태(일이 배정된 상태)에서의 최소 비용.
- 최종적으로 dp[n][(1 << (n + 1)) - 2] 값이 정답을 구할 수 있다.
---
**문제 난이도**\
Gold 4
**문제 유형**\
수학
배열 정렬 후, 두 가지 경우를 모두 고려해야한다.
- 큰 값 조합: arr[n - 1] + arr[i - 1] - 2 × arr[i]
- 작은 값 조합: arr[0] + arr[i + 1] - 2 × arr[i]
왜냐하면 양수일때는 크면 클수록 정답에 가깝지만 음수일때는 작으면 작을 수록 가깝기 때문이다.(절댓갑 이)
각 경우의 절댓값을 비교해서 최대값을 answer 로 갱신.
---
**문제 난이도**\
Gold 4
**문제 유형**\
MST
- 간선 정보를 road[][] 에 저장 후, 비용 기준 오름차순 정렬.
- 크루스칼(Kruskal) 알고리즘 + 유니온 파인드(Union-Find) 로 MST 구성.
- MST 를 완성하면서 minCost …
> [문한결-12주차 알고리즘 스터디] 

- 이종환/12주차/도시_건설.java
- 이종환/12주차/세_수_두_M.java
- 이종환/12주차/소셜네트워킹_어플리케이션.java
- 이종환/12주차/할일_정하기1.java
(n과 홍길동은 본인에 맞게 바꿔주세요! 바꾸시고 이 문장을 지워주세요.)
---
---
**문제 난이도**
골드4
**문제 유형**
`시뮬레이션`
**접근 방식 및 풀이**
---
**문제 난이도**
골드1
**문제 유형**
`DP`
**접근 방식 및 풀이**
여러가지가 있을 수 있으나 결국 'i번째까지 일을 특정 사람들이 하였을 때 최솟값'을 알면 되는 것이다.
그렇기에 TSP 문제처럼 비트마스킹을 이용하여 현재 정보를 저장해나가며 문제를 해결하였다.
```java
static int[][] dp; //dp[i][j] -> i번째 일까지 j 비트마스킹을 통해 표현된 사람들이 했을 때 최솟값  
static int[][] work; // work[i][j] i번 사람이 j번 일을 할 때 비용
for (int i = 0; i < num-1; i++) {
for (int j = 0; j < size; j++) {
if (dp[i][j] == INF) continue;
for (int k = 0; k < num; k++) {
int tNum = j | (1<<k);
if (tNum == j) continue;
dp[i+1][tNum] = Math.min(dp[i+1][tNum],dp[i][j] + work[k][i+1]);
}
}
}
```
---
**문제 난이도**
골드4
**문제 유형**
`수학`
**접근 방식 및 …
> [이종환-12주차 알고리즘 스터디]

- 이종환/11주차/계단수.java
- 이종환/11주차/반도체설계.java
- 이종환/11주차/일감호에_다리놓기.java
- 이종환/11주차/전화돌리기.java
- 이종환/13주차/경사로.java
- 이종환/13주차/로봇청소기.java
- 이종환/13주차/세수의합.java
---
---
2주간 정신이 없어서 제대로 하질 못했습니다 ㅠㅠ 이번주부터 다시 열심히 하겠습니다
**문제 난이도**
**문제 유형**
**접근 방식 및 풀이**
---
**문제 유형**
**접근 방식 및 풀이**
---
**문제 유형**
**접근 방식 및 풀이**
---
**문제 유형**
**접근 방식 및 풀이**
---
**문제 유형**
**접근 방식 및 풀이**
> [이종환-13주차 알고리즘 스터디]

- 문한결/13주차/경사로.java
- 문한결/13주차/로봇청소기.java
- 문한결/13주차/세수.java
- 문한결/13주차/이모티콘.java
---
(이번주도 금요일,다음주 월요일 면접, 일요일 정처기 이슈로 인해서 세용액은 못 풀었네요...  다음주부터는 정상화해보겠습니다!)
---
**문제 난이도**
골드4
**문제 유형**
`HashMap,Set`
**접근 방식 및 풀이**
x+y=k-z를 이용해서 구하면 되는 문제이다.
먼저 x+y를 모든 배열을 두번돌면서(n**2) 리스트에 저장해두고, 동시에 k-z를 set에 넣어둔다.
k-z를 키로 하고 k를 밸류로 하는 map도 만들어서, 집합이 될때의 k의 최댓값을 구한다.
---
**문제 난이도**
골드5
**문제 유형**
`구현, 시물레이션`
**접근 방식 및 풀이**
기본적으로 아래와 같은 코드 로직으로 동작한다.
```java
while(true) {
if(cleanAtCurrentPos(robotX,robotY))continue;
if(!isExistNotClean(robotX,robotY)) {
if(!executeStep2(robotX,robotY))return;
}else {
executeStep3(robotX,robotY);
}
}
```
문제에서 주어진 조건을 순서대로 구현하면 된다.
OOB구현을 잘못해서 시간이 오래 걸렸다.. 확실히 구현 문제는 실수를 얼마나 덜하냐의 싸움 인것 같음
---
**문제 난이도**
골드3
**문제 유형**
구현
**접근 방식 및 풀이**
해당 문제의 핵심아이디어는 아래와 같다.
- 각 행과 열을 각각 검사해서 경사로를 놓을 수 있는지 판단 …
> [문한결-13주차 알고리즘 스터디]

- 박준서/13주차/[Baekjoon-14226]이모티콘.java
- 박준서/13주차/[Baekjoon-14503]로봇청소기.java
- 박준서/13주차/[Baekjoon-14890]경사로.java
- 박준서/13주차/[Baekjoon-2295]세수의합.java
- 박준서/13주차/[Baekjoon-2473]세용액.java
---
---
**문제 난이도**\
Gold 4
**문제 유형**\
구현
현재 위치가 청소되지 않았다면 청소합니다 (matrix[y][x] = 2로 표시).\
현재 방향을 기준으로 왼쪽부터 차례대로 탐색하여 청소할 공간을 찾습니다.\
청소할 공간이 있으면 그 방향으로 회전하고 한 칸 전진합니다.\
네 방향 모두 청소가 되어있거나 벽이면 현재 방향을 유지한 채 한 칸 후진합니다.\
후진도 할 수 없다면 작동을 멈춥니다.
방향이 0:상,1:우,2:하,3:좌 이지만\
실질적으로 구현은 반대 방향임을 유의
---
**문제 난이도**\
Gold 4
**문제 유형**\
그리디, 이분탐색
N^3으로 진행하면 안될 것 같아서\
이분탐색을 활용해 N^2 LogN 으로 진행했지만 시간초과
a + b + c = d -> a + b = d - c 로 변환해서 풀이해야 함\
이 경우 N^2에 해결할 수 있다
---
**문제 난이도**\
Gold 3
**문제 유형**\
구현
경사로 설치 가능 여부 확인:\
높이가 같은 경우: 연속된 칸의 수를 증가시킵니다.\
높이가 1 증가하는 경우(오르막): 이전에 연속된 칸의 수가 X 이상이어야 합니다.\
높이가 1 감소하는 경우(내리막): 앞으로 X개의 칸이 모두 같은 높이여야 합니다.\
높이 차이가 1보다 크면: 지나갈 수 없습니다.
주요 로직\
check 메소드는 한 줄(행 또는 열)이 지나갈 수 있는 길인지 확인합니다:\
현재 높이와 연속된 칸의 수를 추적합니다.\
높이 변화에 …
> [박준서-13주차 알고리즘 스터디]

- 박예진/14주차/[백준 11403] 경로 찾기.cpp
- 박예진/14주차/[백준 11441] 합 구하기.cpp
- 박예진/14주차/[백준 14003] 가장 긴 증가하는 부분 수열.cpp
- 박예진/14주차/[백준 16934] 게임 닉네임.cpp
- 박예진/14주차/[백준 21609] 상어 중학교.cpp
---
---
**문제 난이도**
골드2
**문제 유형**
구현, 시뮬레이션, 
BFS, 우선순위큐
**접근 방식 및 풀이**
1. 가장 큰 블록 그룹 찾기
우선순위큐를 사용해서 정렬을 함께 해주었다.
2단계에서 가장 큰 블록 위치를 제거해주어야 해서
Block 구조체에 개수, 무지개블록 개수,  행, 열, 블록위치를 지정해줬다.
```cpp
struct Value {
int cnt, rainbow, row, col;
vector<Node> pos;
};
struct cmp {
bool operator()(const Value &v1, const Value &v2) {
if (v1.cnt != v2.cnt) return v1.cnt < v2.cnt;
else if (v1.rainbow != v2.rainbow) return v1.rainbow < v2.rainbow;
else if (v1.row != v2.row) return v1.row < v2.row;
return v1.col < v2.col;
}
};
priority_queue<Value, vector<Value>, cmp> pq;
for(int k = 1; k <= M; k++){
memset(visited, 0, sizeof(visited));
for(int i = 0; i < N; i++){
for(int j = 0; j < N; j++){
if (!visited[i][j] && arr[i][j] == k){
Value value = …
```
> [박예진-14주차 알고리즘 스터디]

- 이종환/14주차/가장_긴_증가하는_부분_수열_5.java
- 이종환/14주차/게임_닉네임.java
- 이종환/14주차/경로_찾기.java
- 이종환/14주차/상어_중학교.java
- 이종환/14주차/합_구하기.java
---
---
**문제 난이도**
`골드2`
**문제 유형**
`구현`,`BFS`
**접근 방식 및 풀이**
로직에 맞춰 메서드를 분리 후, 하나씩 구현하였다.
-  BFS 기반으로 어느 블록 그룹을 제거할 지 결정하는 `processAboutBlock()`
-  중력을 적용하는 `applyGravity()`
-  배열을 회전시키는 `turn()`'
이때 블록이 사라지는 것은 -2로 표기하였다.
```java
private static boolean processAboutBlock() {
maxBSize = 0;
maxRbCnt = 0;
visited = new boolean[size][size];
for (int i = 0; i < size; i++) {
for (int j = 0; j < size; j++) {
if(arr[i][j] > -1 && arr[i][j] != 0 && !visited[i][j]){
findBiggestBlock(i,j,arr[i][j]);
}
}
}
if (maxBSize < 2) return false;
removeBlock();
totalPoint += maxBSize*maxBSize;
return true;
}
private static void findBiggestBlock(int y, int x, int target) {
int curSize = 1;
int curRbCnt = 0;
boolean[][] tempVisited = new …
```
> [이종환-14주차 알고리즘 스터디]

- 박준서/13주차/[Baekjoon-14226]이모티콘.java
- 박준서/13주차/[Baekjoon-14503]로봇청소기.java
- 박준서/13주차/[Baekjoon-14890]경사로.java
- 박준서/13주차/[Baekjoon-2295]세수의합.java
- 박준서/13주차/[Baekjoon-2473]세용액.java
- 박준서/14주차/[Baekjoon-11403]경로찾기.java
- 박준서/14주차/[Baekjoon-11441]합구하기.java
- 박준서/14주차/[Baekjoon-14003]가장긴증가하는부분수열5.java
- 박준서/14주차/[Baekjoon-16934]게임닉네임.java
- 박준서/14주차/[Baekjoon-21609]상어중학교.java
---
---
**문제 난이도**\
Gold 2
**문제 유형**\
구현
1. 그룹 탐색
→ 모든 일반 블록에서 BFS로 유효한 그룹 수집
2. 그룹 선택
→ 크기/무지개 수/기준 블록으로 정렬 → 최우선 그룹 선택
3. 블록 제거 & 점수 획득
→ 선택 그룹 삭제 → ans에 점수 누적
4. 중력 적용
→ 빈 공간을 채우도록 블록 아래로 이동
5. 보드 회전
→ 반시계 90도 회전으로 새로운 배치 생성
6. 중력 재적용
→ 회전 후 다시 블록 정렬
더 이상 그룹이 없을 때까지 1~6 반복
정렬 조건에 유의하여 철저히 검증하는 것이 좋다
---
**문제 난이도**\
Gold 3
**문제 유형**\
Trie
Trie(트라이) 자료구조를 사용하여 문자열을 저장\
문자열을 삽입할 때, 새로운 노드가 생성되는 최초 지점의 부분 문자열을 출력\
이미 존재하는 문자열이라면 이후에 전체 문자열과 등장 횟수를 출력
---
**문제 난이도**\
Platinum 5
**문제 유형**\
LIS, LCS
현재 원소가 LIS의 마지막보다 크면 LIS 확장\
아니면 이분 탐색으로 LIS 배열에서 갱신할 위치를 찾아서 값 교체
LIS 길이 및 원소 역추적을 위해\
idx 배열을 이용해 실제 LIS 원소를 역추적하여 스택에 저장 후 출력
---
**문제 난이도**\
Silver 1
**문제 유형**\
플로이드-워샬
인접 행렬을 입력받아, matrix[i][j]에 1(연결됨) 또는 매우 큰 값(연결 안 됨)을 저장\
모든 정점 …
> [박준서-14주차 알고리즘 스터디]

- 문한결/14주차/게임닉네임.java
- 문한결/14주차/경로찾기.java
- 문한결/14주차/상어중학교.java
- 문한결/14주차/증가하는수열.java
- 문한결/14주차/합구하기.java
---
---
**문제 유형**: ```플로이드 워셜 ``` 
**문제 난이도**: 실버 1
**접근 및 풀이**:  
모든 중간 노드를 기준으로 출발지와 도착지를 연결할 수 있는지 확인했다.  
중간 노드 i를 거쳐서 j → i → k로 갈 수 있으면, j → k로도 갈 수 있게 `arr[j][k] = 1`로 업데이트했다.  
3중 for문 구조로, 중간 노드를 가장 바깥에 고정시키는 게 핵심이다.  
모든 경로를 다 업데이트해야 하므로 시간 복잡도는 O(N³)이고, 입력 범위가 작아서 충분히 통과 가능했다.
feat...
여태까지 플로이드 워셜 문제를 잘못 풀고 있었다.. 중간 경유지를 고정해야한다!
---
**문제 유형**: ```누적합```  
**문제 난이도**: 실버 3
**접근 및 풀이**:  
입력으로 주어진 수열을 한 번 순회하면서 누적합 배열을 미리 계산해놨다.  
이후 구간 합을 물어볼 때는 `dp[b] - dp[a-1]` 계산만으로 바로 답할 수 있었다.  
누적합을 미리 만들어 놓으면 쿼리당 O(1) 시간만 소요돼서, 전체 쿼리 수가 많아도 빠르게 처리가 가능했다.  
구현 자체는 간단하지만, 배열 인덱스 관리 (특히 0번 인덱스) 주의가 필요했다.
---
**문제 유형**: LIS  + 이진탐색  
**문제 난이도**: 플래티넘 5
**접근 및 풀이**:  
O(N log N) 방식으로 LIS를 구했다.  
`tailsVal` 리스트를 만들어 끝 값만 관리하면서, 새로운 …
> [문한결-14주차 알고리즘 스터디]

- 문한결/15주차/나머지합.java
- 문한결/15주차/제곱수의합.java
- 문한결/15주차/행복유치원.java
- 문한결/15주차/후위표기식.java
---
---
**문제 난이도**
골드2
**문제 유형**
```스택```
**접근 방식 및 풀이**
스택을 정말 잘 써야 풀 수 있는 문제가 아닐까 싶다.
우선 문자열을 전체를 돌 때, 문자열에서 피연산자는 바로바로 answer에 넣어준다.
피연산자가 아닐 때는 다시, )와 )가 아닌 연산자로 나뉘며, )가 아닌 연산자는 기본적으로 후위 표기식에서 나타낼 때,
우선순위들을 가진다.
이를 이용해서 각 연산자들의 우선순위를 아래와 같이 Map에 저장해둔다.
```java
priorMap.put("+", 1);
priorMap.put("-", 1);
priorMap.put("*", 2);
priorMap.put("/", 2);
priorMap.put("(", 3);
```
그 후 현제 나온 문자가 스택의 가장 위에 있는 문자보다 우선순위가 작거나 같다면, 스택에 있는 문자가 더 먼저 후위 표기식에서는 나와야 하므로, 스택의 가장 위에 있는 문자가 더 작은 우선순위를 가지거나 스택에 빌 때까지  스택에서 pop한다.
pop후 현재 문자를 answer에 넣어준다.
)인 경우에는 가장 큰 우선순위를 가지므로, (가 나올 때 까지 pop해서 답으로 넣어주면 된다.
```ArrayDeque```에서 스택을 구현하려면, ```removeLast``` ,```peekLast```를 사용해야함을 유의하자.
---
**문제 난이도**
실버1
**문제 유형**
```DP```
**접근 방식 및 풀이**
n이 크지 않기 …
> [문한결-15주차 알고리즘 스터디]

- 박준서/15주차/[Baekjoon-10986]나머지합.java
- 박준서/15주차/[Baekjoon-13164]행복유치원.java
- 박준서/15주차/[Baekjoon-1699]제곱수의합.java
- 박준서/15주차/[Baekjoon-1918]후위표기식.java
- 박준서/15주차/[Baekjoon-23289]온풍기안녕!.java
---
---
**문제 난이도**\
Platinum 5
**문제 유형**\
구현
주어진 조건에 따라 구현하면 되지만\
구현 조건이 까다로워서 오래걸렸다\
아마 같은 이유로 난이도도 높게 책정된 것 같다
while(초콜릿<=100){\
&emsp;온풍기 바람 퍼뜨리기\
&emsp;인접 칸 온도 조절\
&emsp;외벽 온도 감소\
&emsp;목표 온도 달성 검사\
&emsp;초콜릿 1개 증가\
}
---
**문제 난이도**\
Gold 3
**문제 유형**\
Stack
후위표기식을 먼저 공부해야 풀 수 있는 문제\
피연산자 A,B,C ... 는 바로바로 출력\
(), \*/, +- 우선순위
스택의 peek()가 현재보다 우선순위가 높거나 같다면 저장,\
낮다면 출력\
')'는 '('가 나올때까지 모두 출력
---
**문제 난이도**\
Gold 5
**문제 유형**\
그리디
입력은 정렬된 상태로 주어지기 때문에 차례대로 받으면서 거리 저장\
(코드에 정렬 로직은 없으나 문제 조건에 따라 가정)
인접 센서 거리 계산: 모든 인접 센서 간의 거리를 우선순위 큐에 저장\
M개의 집중국을 설치하면 (M-1)개의 가장 큰 간격을 제거\
남은 (N-M)개의 가장 작은 간격들의 합이 최소 신호 합
---
**문제 난이도**\
Gold 3
**문제 유형**\
수학
입력을 받으면서 누적합을 계속 더하고, M으로 나눈 나머지를 구함\
해당 나머지의 개수를 증가시킴\
누적합이 0이거나, 이전에 같은 나머지가 나왔던 횟수만큼 …
> [박준서-15주차 알고리즘 스터디]

- 이종환/16주차/GLCCDM.java
- 이종환/16주차/HJS.java
- 이종환/16주차/ZOAC_7.java
- 이종환/16주차/강의실.java
- 이종환/16주차/골드바흐흑흙의_추측.java
- 이종환/16주차/트리와쿼리_10의9승.java
---
---
**문제 난이도**
`골드1`
**문제 유형**
`DP`
**접근 방식 및 풀이**
0,0부터 (height-1,width-1) 한 번 움직일때 각각의 칸에서 최댓값을 dp[][][]에 보관.
그리고 반대로   (height-1,width-1) 에서 (0,0)으로 움직일때의 최댓값을 reverseDp[][][]에 보관하였다. 
이를 이용해
dp[height-1][i][k] + reverseDp[0][i+1][k] 과
dp[i][width-1][k] + reverseDp[i+1][0][k]  중 최댓값을 구하였다.
```java
private static void findHighest() {
for (int k = 0; k < 4; k++) {
ans[k] =  dp[height-1][width-1][k];
for (int i = 0; i < width-1; i++) {
ans[k] = Math.max(ans[k], dp[height-1][i][k] + reverseDp[0][i+1][k]);
}
for (int i = 0; i < height-1; i++) {
ans[k] = Math.max(ans[k], dp[i][width-1][k] + reverseDp[i+1][0][k]);
}
}
}
```
---
**문제 난이도**
골드3
**문제 유형**
`트리` , `자료구조`
**접근 방식 및 풀이** …
> [이종환-16주차 알고리즘 스터디]

- 박준서/16주차/[Baekjoon-30046]HJS.java
- 박준서/16주차/[Baekjoon-30050]트리와쿼리10^9.java
- 박준서/16주차/[Baekjoon-31872]강의실.java
- 박준서/16주차/[Baekjoon-32647]골드바흐흑흙의추측.java
- 박준서/16주차/[Baekjoon-32648]ZOAC7.java
- 박준서/16주차/[Baekjoon-32649]GLCCDM.java
---
---
**문제 난이도**\
Gold 1
**문제 유형**\
DP
DP로 풀어야 겠다는 아이디어가 떠오르면 쉬운문제인 것 같다
(0,0) -> (N,M), (N,M) -> (0,0) 두 경우를 따로 만들었고\
각 지점은 그 지접에서 목표지까지 문자 수
(0,0) -> (N,M) 방향에서 모든 지점을 탐색\
max((i+1,1)에서 오른쪽 아래로 가는 경로, (1,j+1)에서 오른쪽 아래로 가는 경로)
```java
ans = Math.max(ans, DP[1][k][i][j] + Math.max(DP[0][k][i + 1][1], DP[0][k][1][j + 1]));
```
---
**문제 난이도**\
Gold 3
**문제 유형**\
LCM, Map
기본적으로 이진 트리 구조를 가정하며, 노드 n의 부모는 n/2\
따라서 초기에는 이 규칙을 따르기 떄문에 저장 안해도 됨\
변경분만 Map에 저장해서 관리
트리 구조 변경할 떄 같은 레벨에 붙지 않을 수 있어서\
노드 본인의 레벨을 찾는 메서드도 만들어 썼다.\
레벨을 찾았으면 LCA로 트리를 오르면서 모든 수를 더해주면 됨
---
**문제 난이도**\
Silver 3
**문제 유형**\
그리디
처음에는 GCD, LCM 값을 곱한 후 진행했음 -> 아마 시간초과\
소인수 분해를 통해 만들 수 있는 수의 가지수를 찾고\
출력의 순서가 상관없고 어떤 케이스를 출력하든 정답이라서\
GCD, LCM, 나머지 약수 를 출력하면 된다
---
**문제 …
> [박준서-16주차 알고리즘 스터디]

- 문한결/16주차/GLCCDM.java
- 문한결/16주차/HJS.java
- 문한결/16주차/LectureRoom.java
- 문한결/16주차/TreeAndQuery.java
- 문한결/16주차/ZOAC.java
---
---
**문제 난이도**
실버3
**문제 유형**
```구현```
**접근 방식 및 풀이**
- 최소공배수와, 최대 공약수를 이용해서 되는 경우의 수를 찾는 문제.
- 즉, A와 B가 주어졌을 때, A로 나눈 값 C를 만들 수 있는 K개의 수열을 찾는 문제임.
- B가 A로 나누어떨어지지 않으면 -1 출력.
- C의 모든 약수를 구한 뒤, K개를 뽑아 GCD가 1이고 LCM이 C가 되는 경우를 DFS로 탐색.
- 조건을 만족하는 조합이 나오면 A를 곱해서 결과 출력하면 답이다.
내가 어렵게 푼건지 몰라도 이게 실버라고..? 싶은 문제
---
**난이도** 
실버3
**문제 유형**
```구현```
**접근 방식 및 풀이**
- 세 줄의 문자열이 주어지고, 어떤 두 줄 사이에만 다른 글자가 있을 경우 'HJS!'를 출력하면된다.
- 첫째-둘째, 둘째-셋째 줄 비교해서 각각 다른 문자 위치를 기록하고, 조건에 따라 출력 결정해서 답을 구하면된다.
---
**난이도** 
실버3
**문제 유형**
```정렬```
**접근 방식 및 풀이**
- n개의 강의 시간이 주어지고, k개의 그룹으로 나눌 때 최소 차이합을 구하는 문제.
- 정렬 후 인접한 원소 간 차이를 배열로 만든 다음, 그 중 가장 큰 k-1개의 차이를 빼고 나머지를 더하면 된다.
- 그 무슨 유치원??(키 순서대로 서서 그룹 나누는) 문제가 생각났다.
---
**문제 난이도**
골드3
**문제 유형**
```트리```,```Map``` …
> [문한결-16주차 알고리즘 스터디]
